package com.doerit.util;

public enum SessionKey {
	SESSION_EMPLOYEE,
	SESSION_USER_ACCOUNT,
	SESSION_USER,
	SESSION_CREATE_USER_ACCOUNT,
	SESSION_EMPLOYEE_USER,
	HISTORY_ACTION,
	RESPONSE,
	PATIENT_DIAGNOSTIC,
	PATIENT_TEETH_DISORDER,
	PREVIEW_VISITED;
}