CREATE TABLE `tbl_patient_diagnostic_drughistory` (
  `ID` char(32) NOT NULL,
  `PATIENT_ID` char(32) DEFAULT NULL,
  
  `ANTICOAGULANT_WARFARIN` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_WARFARIN_DOSE` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_WARFARIN_FREQUENCY` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_WARFARIN_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_CLOPIDOGREL` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_CLOPIDOGREL_DOSE` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_CLOPIDOGREL_FREQUENCY` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_CLOPIDOGREL_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_ASPIRIN` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_ASPIRIN_DOSE` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_ASPIRIN_FREQUENCY` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_ASPIRIN_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_OTHER` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_OTHER_DETAIL` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_OTHER_DOSE` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_OTHER_FREQUENCY` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ANTICOAGULANT_OTHER_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `RADIATIONTHERAPY` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `RADIATIONTHERAPY_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `COMMENTS` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  
  
  
  `COMMENT` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '0',
  `SORT_ORDER` int(6) DEFAULT '1',
  `INSERT_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `INSERT_DATETIME` datetime DEFAULT NULL,
  `UPDATE_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `UPDATE_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
