CREATE TABLE `tbl_patient_diagnostic_dietary_habits` (
  `ID` char(32) NOT NULL,
  `PATIENT_ID` char(32) DEFAULT NULL,
  
  `SUGAR_CONSUMPTION` char(255) DEFAULT NULL,
  `BEVERAGE_CARBONIC` char(255) DEFAULT NULL,
  `BEVERAGE_FRUIT` char(255) DEFAULT NULL,
  `OTHER` char(255) DEFAULT NULL,
  `EMPLOYMENT` char(255) DEFAULT NULL,

  
  `COMMENT` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '0',
  `SORT_ORDER` int(6) DEFAULT '1',
  `INSERT_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `INSERT_DATETIME` datetime DEFAULT NULL,
  `UPDATE_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `UPDATE_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
