CREATE TABLE `tbl_patient_diagnostic_complaint` (
  `ID` char(32) NOT NULL,
  `PATIENT_ID` char(32) DEFAULT NULL,
  `DEPARTMENT` char(128) DEFAULT NULL,
  `SUPERVISOR` char(128) DEFAULT NULL,
  `COMPLAINT` text DEFAULT NULL,
  `COMPLAINT_TYPE` text DEFAULT NULL,
  `COMPLAINT_HISTORY` text DEFAULT NULL,
  
  `COMMENT` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '0',
  `SORT_ORDER` int(6) DEFAULT '1',
  `INSERT_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `INSERT_DATETIME` datetime DEFAULT NULL,
  `UPDATE_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `UPDATE_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
