CREATE TABLE `tbl_patient_diagnostic_brushing_habits` (
  `ID` char(32) NOT NULL,
  `PATIENT_ID` char(32) DEFAULT NULL,
  
  `BRUSHING_TOOL` char(255) DEFAULT NULL,
  `BRUSHING_TOOL_OTHER` char(255) DEFAULT NULL,
  `TOOTHPASTE` char(255) DEFAULT NULL,
  `TOOTHPASTE_OTHER` text DEFAULT NULL,
  `BRUSHING_FREQUENCY` char(255) DEFAULT NULL,
  `BRISTLES` char(255) DEFAULT NULL,
  `BRUSHING_DURATION` char(255) DEFAULT NULL,
  `SUPPLEMENT_NONE` char(255) DEFAULT NULL,
  `SUPPLEMENT_FLOSS` char(255) DEFAULT NULL,
  `SUPPLEMENT_BOTTLE_BRUSHES` char(255) DEFAULT NULL,
  `SUPPLEMENT_SINGLE_TUFT` char(255) DEFAULT NULL,
  `SUPPLEMENT_WOODPICKS` char(255) DEFAULT NULL,
  `SUPPLEMENT_IRRIGATORS` char(255) DEFAULT NULL,
  `SUPPLEMENT_OTHER` text DEFAULT NULL,
  
  
  `COMMENT` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '0',
  `SORT_ORDER` int(6) DEFAULT '1',
  `INSERT_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `INSERT_DATETIME` datetime DEFAULT NULL,
  `UPDATE_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `UPDATE_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
