CREATE TABLE `tbl_patient_diagnostic_habits2` (
  `ID` char(32) NOT NULL,
  `PATIENT_ID` char(32) DEFAULT NULL,

  `ALCOHOL` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALCOHOL_SPIRITS` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALCOHOL_SPIRITS_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALCOHOL_WINE` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALCOHOL_WINE_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALCOHOL_BEER` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALCOHOL_BEER_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALCOHOL_LOCAL` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALCOHOL_LOCAL_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_BRUXISM` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_BRUXISM_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_CLENCHING` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_CLENCHING_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_NAIL_LIP_BITING` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_NAIL_LIP_BITING_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_BITING_OBJECTS` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_BITING_OBJECTS_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_CHEWING` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_CHEWING_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_NON_NUTRIVE_SUCKING` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_NON_NUTRIVE_FINGER_SUCKING` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_NON_NUTRIVE_FINGER_SUCKING_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_NON_NUTRIVE_THUMB_SUCKING` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_NON_NUTRIVE_THUMB_SUCKING_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_NON_NUTRIVE_DUMMY_SUCKING` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARAFUNCTIONAL_NON_NUTRIVE_DUMMY_SUCKING_DURATION` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  
  
  
  
  `COMMENT` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '0',
  `SORT_ORDER` int(6) DEFAULT '1',
  `INSERT_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `INSERT_DATETIME` datetime DEFAULT NULL,
  `UPDATE_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `UPDATE_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
