CREATE TABLE `tbl_patient_diagnostic_medicalrecord3` (
  `ID` char(32) NOT NULL,
  `PATIENT_ID` char(32) DEFAULT NULL,
  `GASTRO_INTESTINAL_ULCERS` char(255) DEFAULT NULL,
  `GASTRO_INTESTINAL_GASTRICREFLUX` char(255) DEFAULT NULL,
  `GASTRO_INTESTINAL_OTHER` char(255) DEFAULT NULL,
  `GASTRO_INTESTINAL_OTHER_COMMENTS` text DEFAULT NULL,
  `HEPATITIS_A` char(255) DEFAULT NULL,
  `HEPATITIS_B` char(255) DEFAULT NULL,
  `HEPATITIS_C` char(255) DEFAULT NULL,
  `HEPATITIS_OTHER` text DEFAULT NULL,
  `HEPATITIS_OTHER_COMMENTS` text DEFAULT NULL,
  `HIV` char(255) DEFAULT NULL,
  `HYPERTENSION` char(255) DEFAULT NULL,
  `LIVER_DISORDERS` char(255) DEFAULT NULL,
  `MUSCULO_SKELETAL_ARTHRITIS` char(255) DEFAULT NULL,
  `MUSCULO_SKELETAL_JOINTREPLACEMENT` char(255) DEFAULT NULL,
  `MUSCULO_SKELETAL_OTHER` text DEFAULT NULL,
  `MUSCULO_SKELETAL_OTHER_COMMENTS` text DEFAULT NULL,
  `NEUROLOGICAL_DISORDERS_MIGRAINE` char(255) DEFAULT NULL,
  `NEUROLOGICAL_DISORDERS_NEURALGIC` char(255) DEFAULT NULL,
  
  
  
  
  `COMMENT` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '0',
  `SORT_ORDER` int(6) DEFAULT '1',
  `INSERT_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `INSERT_DATETIME` datetime DEFAULT NULL,
  `UPDATE_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `UPDATE_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
