CREATE TABLE `tbl_patient_diagnostic_medicalrecord4` (
  `ID` char(32) NOT NULL,
  `PATIENT_ID` char(32) DEFAULT NULL,
  `BEHAVIOURAL_DISORDERS` char(255) DEFAULT NULL,
  `TMD` char(255) DEFAULT NULL,
  `TMD_OTHER` char(255) DEFAULT NULL,
  `RENAL_DISORDERS_CHRONICINFECTIONS` char(255) DEFAULT NULL,
  `RENAL_DISORDERS_KIDNEYFAILURE` char(255) DEFAULT NULL,
  `RENAL_DISORDERS_TRANSPLANT` char(255) DEFAULT NULL,
  `RENAL_DISORDERS_OTHER` char(255) DEFAULT NULL,
  `PREGNANCY` char(255) DEFAULT NULL,
  `ON_HORMONAL_CONTRACEPTIVES` char(255) DEFAULT NULL,
  `OTHER_COMMENTS` text DEFAULT NULL,
    
  
  
  
  `COMMENT` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '0',
  `SORT_ORDER` int(6) DEFAULT '1',
  `INSERT_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `INSERT_DATETIME` datetime DEFAULT NULL,
  `UPDATE_USER_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `UPDATE_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
