package com.doerit.model;

import java.util.Date;

public class Document implements InsertUpdate {
    
	private String id;
    private String documentCategory;
    private String entityName;
    private String entityId;
    private String docuementDescription;
    private String fileName;
    private String contentType;
    private Integer sortOrder;
    private Byte state;
    private String insertUserId;
    private Date insertDatetime;
    private String updateUserId;
    private Date updateDatetime;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.ID
     *
     * @param id the value for tbl_document.ID
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.DOCUMENT_CATEGORY
     *
     * @return the value of tbl_document.DOCUMENT_CATEGORY
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public String getDocumentCategory() {
        return documentCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.DOCUMENT_CATEGORY
     *
     * @param documentCategory the value for tbl_document.DOCUMENT_CATEGORY
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setDocumentCategory(String documentCategory) {
        this.documentCategory = documentCategory == null ? null : documentCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.ENTITY_NAME
     *
     * @return the value of tbl_document.ENTITY_NAME
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.ENTITY_NAME
     *
     * @param entityName the value for tbl_document.ENTITY_NAME
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName == null ? null : entityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.ENTITY_ID
     *
     * @return the value of tbl_document.ENTITY_ID
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.ENTITY_ID
     *
     * @param entityId the value for tbl_document.ENTITY_ID
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setEntityId(String entityId) {
        this.entityId = entityId == null ? null : entityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.DOCUEMENT_DESCRIPTION
     *
     * @return the value of tbl_document.DOCUEMENT_DESCRIPTION
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public String getDocuementDescription() {
        return docuementDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.DOCUEMENT_DESCRIPTION
     *
     * @param docuementDescription the value for tbl_document.DOCUEMENT_DESCRIPTION
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setDocuementDescription(String docuementDescription) {
        this.docuementDescription = docuementDescription == null ? null : docuementDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.FILE_NAME
     *
     * @return the value of tbl_document.FILE_NAME
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.FILE_NAME
     *
     * @param fileName the value for tbl_document.FILE_NAME
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.CONTENT_TYPE
     *
     * @return the value of tbl_document.CONTENT_TYPE
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.CONTENT_TYPE
     *
     * @param contentType the value for tbl_document.CONTENT_TYPE
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.SORT_ORDER
     *
     * @return the value of tbl_document.SORT_ORDER
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.SORT_ORDER
     *
     * @param sortOrder the value for tbl_document.SORT_ORDER
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.STATE
     *
     * @return the value of tbl_document.STATE
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.STATE
     *
     * @param state the value for tbl_document.STATE
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.INSERT_USER_ID
     *
     * @return the value of tbl_document.INSERT_USER_ID
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_document.INSERT_USER_ID
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.INSERT_DATETIME
     *
     * @return the value of tbl_document.INSERT_DATETIME
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_document.INSERT_DATETIME
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.UPDATE_USER_ID
     *
     * @return the value of tbl_document.UPDATE_USER_ID
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_document.UPDATE_USER_ID
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_document.UPDATE_DATETIME
     *
     * @return the value of tbl_document.UPDATE_DATETIME
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_document.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_document.UPDATE_DATETIME
     *
     * @mbggenerated Thu Aug 31 22:51:22 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

}