package com.doerit.model;

import java.util.Date;

public class PatientDiagnosticHabits1 implements InsertUpdate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.PATIENT_ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String patientId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_BETEL
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String betelQuidIngredientsBetel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_LIME
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String betelQuidIngredientsLime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String betelQuidIngredientsTobacco;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECA_PRODUCTS
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String betelQuidIngredientsArecaProducts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECANUT
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String betelQuidIngredientsArecanut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO_PRODUCTS
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String betelQuidIngredientsTobaccoProducts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_OTHER
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String betelQuidIngredientsOther;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.BETEL_QUID_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String betelQuidFrequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.BETEL_QUID_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String betelQuidDuration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smoking;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingCigarettes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingCigarettesDuration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingCigarettesFrequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_CIGAR
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingCigar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_CIGAR_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingCigarDuration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_CIGAR_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingCigarFrequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_BEEDI
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingBeedi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_BEEDI_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingBeediDuration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_BEEDI_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingBeediFrequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_PIPE
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingPipe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_PIPE_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingPipeDuration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_PIPE_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingPipeFrequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_ROLLUP
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingRollup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingRollupDuration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String smokingRollupFrequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.COMMENT
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.STATUS
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.SORT_ORDER
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.INSERT_USER_ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String insertUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.INSERT_DATETIME
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.UPDATE_USER_ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private String updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_diagnostic_habits1.UPDATE_DATETIME
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.ID
	 * @return  the value of tbl_patient_diagnostic_habits1.ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.ID
	 * @param id  the value for tbl_patient_diagnostic_habits1.ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.PATIENT_ID
	 * @return  the value of tbl_patient_diagnostic_habits1.PATIENT_ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getPatientId() {
		return patientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.PATIENT_ID
	 * @param patientId  the value for tbl_patient_diagnostic_habits1.PATIENT_ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setPatientId(String patientId) {
		this.patientId = patientId == null ? null : patientId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_BETEL
	 * @return  the value of tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_BETEL
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getBetelQuidIngredientsBetel() {
		return betelQuidIngredientsBetel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_BETEL
	 * @param betelQuidIngredientsBetel  the value for tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_BETEL
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setBetelQuidIngredientsBetel(String betelQuidIngredientsBetel) {
		this.betelQuidIngredientsBetel = betelQuidIngredientsBetel == null ? null : betelQuidIngredientsBetel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_LIME
	 * @return  the value of tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_LIME
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getBetelQuidIngredientsLime() {
		return betelQuidIngredientsLime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_LIME
	 * @param betelQuidIngredientsLime  the value for tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_LIME
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setBetelQuidIngredientsLime(String betelQuidIngredientsLime) {
		this.betelQuidIngredientsLime = betelQuidIngredientsLime == null ? null : betelQuidIngredientsLime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO
	 * @return  the value of tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getBetelQuidIngredientsTobacco() {
		return betelQuidIngredientsTobacco;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO
	 * @param betelQuidIngredientsTobacco  the value for tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setBetelQuidIngredientsTobacco(String betelQuidIngredientsTobacco) {
		this.betelQuidIngredientsTobacco = betelQuidIngredientsTobacco == null ? null
				: betelQuidIngredientsTobacco.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECA_PRODUCTS
	 * @return  the value of tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECA_PRODUCTS
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getBetelQuidIngredientsArecaProducts() {
		return betelQuidIngredientsArecaProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECA_PRODUCTS
	 * @param betelQuidIngredientsArecaProducts  the value for tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECA_PRODUCTS
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setBetelQuidIngredientsArecaProducts(String betelQuidIngredientsArecaProducts) {
		this.betelQuidIngredientsArecaProducts = betelQuidIngredientsArecaProducts == null ? null
				: betelQuidIngredientsArecaProducts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECANUT
	 * @return  the value of tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECANUT
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getBetelQuidIngredientsArecanut() {
		return betelQuidIngredientsArecanut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECANUT
	 * @param betelQuidIngredientsArecanut  the value for tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_ARECANUT
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setBetelQuidIngredientsArecanut(String betelQuidIngredientsArecanut) {
		this.betelQuidIngredientsArecanut = betelQuidIngredientsArecanut == null ? null
				: betelQuidIngredientsArecanut.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO_PRODUCTS
	 * @return  the value of tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO_PRODUCTS
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getBetelQuidIngredientsTobaccoProducts() {
		return betelQuidIngredientsTobaccoProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO_PRODUCTS
	 * @param betelQuidIngredientsTobaccoProducts  the value for tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_TOBACCO_PRODUCTS
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setBetelQuidIngredientsTobaccoProducts(String betelQuidIngredientsTobaccoProducts) {
		this.betelQuidIngredientsTobaccoProducts = betelQuidIngredientsTobaccoProducts == null ? null
				: betelQuidIngredientsTobaccoProducts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_OTHER
	 * @return  the value of tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_OTHER
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getBetelQuidIngredientsOther() {
		return betelQuidIngredientsOther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_OTHER
	 * @param betelQuidIngredientsOther  the value for tbl_patient_diagnostic_habits1.BETEL_QUID_INGREDIENTS_OTHER
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setBetelQuidIngredientsOther(String betelQuidIngredientsOther) {
		this.betelQuidIngredientsOther = betelQuidIngredientsOther == null ? null : betelQuidIngredientsOther.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_FREQUENCY
	 * @return  the value of tbl_patient_diagnostic_habits1.BETEL_QUID_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getBetelQuidFrequency() {
		return betelQuidFrequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_FREQUENCY
	 * @param betelQuidFrequency  the value for tbl_patient_diagnostic_habits1.BETEL_QUID_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setBetelQuidFrequency(String betelQuidFrequency) {
		this.betelQuidFrequency = betelQuidFrequency == null ? null : betelQuidFrequency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_DURATION
	 * @return  the value of tbl_patient_diagnostic_habits1.BETEL_QUID_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getBetelQuidDuration() {
		return betelQuidDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.BETEL_QUID_DURATION
	 * @param betelQuidDuration  the value for tbl_patient_diagnostic_habits1.BETEL_QUID_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setBetelQuidDuration(String betelQuidDuration) {
		this.betelQuidDuration = betelQuidDuration == null ? null : betelQuidDuration.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmoking() {
		return smoking;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING
	 * @param smoking  the value for tbl_patient_diagnostic_habits1.SMOKING
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmoking(String smoking) {
		this.smoking = smoking == null ? null : smoking.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingCigarettes() {
		return smokingCigarettes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES
	 * @param smokingCigarettes  the value for tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingCigarettes(String smokingCigarettes) {
		this.smokingCigarettes = smokingCigarettes == null ? null : smokingCigarettes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_DURATION
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingCigarettesDuration() {
		return smokingCigarettesDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_DURATION
	 * @param smokingCigarettesDuration  the value for tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingCigarettesDuration(String smokingCigarettesDuration) {
		this.smokingCigarettesDuration = smokingCigarettesDuration == null ? null : smokingCigarettesDuration.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_FREQUENCY
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingCigarettesFrequency() {
		return smokingCigarettesFrequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_FREQUENCY
	 * @param smokingCigarettesFrequency  the value for tbl_patient_diagnostic_habits1.SMOKING_CIGARETTES_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingCigarettesFrequency(String smokingCigarettesFrequency) {
		this.smokingCigarettesFrequency = smokingCigarettesFrequency == null ? null : smokingCigarettesFrequency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGAR
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_CIGAR
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingCigar() {
		return smokingCigar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGAR
	 * @param smokingCigar  the value for tbl_patient_diagnostic_habits1.SMOKING_CIGAR
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingCigar(String smokingCigar) {
		this.smokingCigar = smokingCigar == null ? null : smokingCigar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGAR_DURATION
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_CIGAR_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingCigarDuration() {
		return smokingCigarDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGAR_DURATION
	 * @param smokingCigarDuration  the value for tbl_patient_diagnostic_habits1.SMOKING_CIGAR_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingCigarDuration(String smokingCigarDuration) {
		this.smokingCigarDuration = smokingCigarDuration == null ? null : smokingCigarDuration.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGAR_FREQUENCY
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_CIGAR_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingCigarFrequency() {
		return smokingCigarFrequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_CIGAR_FREQUENCY
	 * @param smokingCigarFrequency  the value for tbl_patient_diagnostic_habits1.SMOKING_CIGAR_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingCigarFrequency(String smokingCigarFrequency) {
		this.smokingCigarFrequency = smokingCigarFrequency == null ? null : smokingCigarFrequency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_BEEDI
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_BEEDI
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingBeedi() {
		return smokingBeedi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_BEEDI
	 * @param smokingBeedi  the value for tbl_patient_diagnostic_habits1.SMOKING_BEEDI
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingBeedi(String smokingBeedi) {
		this.smokingBeedi = smokingBeedi == null ? null : smokingBeedi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_BEEDI_DURATION
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_BEEDI_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingBeediDuration() {
		return smokingBeediDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_BEEDI_DURATION
	 * @param smokingBeediDuration  the value for tbl_patient_diagnostic_habits1.SMOKING_BEEDI_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingBeediDuration(String smokingBeediDuration) {
		this.smokingBeediDuration = smokingBeediDuration == null ? null : smokingBeediDuration.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_BEEDI_FREQUENCY
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_BEEDI_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingBeediFrequency() {
		return smokingBeediFrequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_BEEDI_FREQUENCY
	 * @param smokingBeediFrequency  the value for tbl_patient_diagnostic_habits1.SMOKING_BEEDI_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingBeediFrequency(String smokingBeediFrequency) {
		this.smokingBeediFrequency = smokingBeediFrequency == null ? null : smokingBeediFrequency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_PIPE
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_PIPE
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingPipe() {
		return smokingPipe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_PIPE
	 * @param smokingPipe  the value for tbl_patient_diagnostic_habits1.SMOKING_PIPE
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingPipe(String smokingPipe) {
		this.smokingPipe = smokingPipe == null ? null : smokingPipe.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_PIPE_DURATION
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_PIPE_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingPipeDuration() {
		return smokingPipeDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_PIPE_DURATION
	 * @param smokingPipeDuration  the value for tbl_patient_diagnostic_habits1.SMOKING_PIPE_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingPipeDuration(String smokingPipeDuration) {
		this.smokingPipeDuration = smokingPipeDuration == null ? null : smokingPipeDuration.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_PIPE_FREQUENCY
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_PIPE_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingPipeFrequency() {
		return smokingPipeFrequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_PIPE_FREQUENCY
	 * @param smokingPipeFrequency  the value for tbl_patient_diagnostic_habits1.SMOKING_PIPE_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingPipeFrequency(String smokingPipeFrequency) {
		this.smokingPipeFrequency = smokingPipeFrequency == null ? null : smokingPipeFrequency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_ROLLUP
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_ROLLUP
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingRollup() {
		return smokingRollup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_ROLLUP
	 * @param smokingRollup  the value for tbl_patient_diagnostic_habits1.SMOKING_ROLLUP
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingRollup(String smokingRollup) {
		this.smokingRollup = smokingRollup == null ? null : smokingRollup.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_DURATION
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingRollupDuration() {
		return smokingRollupDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_DURATION
	 * @param smokingRollupDuration  the value for tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_DURATION
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingRollupDuration(String smokingRollupDuration) {
		this.smokingRollupDuration = smokingRollupDuration == null ? null : smokingRollupDuration.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_FREQUENCY
	 * @return  the value of tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getSmokingRollupFrequency() {
		return smokingRollupFrequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_FREQUENCY
	 * @param smokingRollupFrequency  the value for tbl_patient_diagnostic_habits1.SMOKING_ROLLUP_FREQUENCY
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSmokingRollupFrequency(String smokingRollupFrequency) {
		this.smokingRollupFrequency = smokingRollupFrequency == null ? null : smokingRollupFrequency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.COMMENT
	 * @return  the value of tbl_patient_diagnostic_habits1.COMMENT
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.COMMENT
	 * @param comment  the value for tbl_patient_diagnostic_habits1.COMMENT
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setComment(String comment) {
		this.comment = comment == null ? null : comment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.STATUS
	 * @return  the value of tbl_patient_diagnostic_habits1.STATUS
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.STATUS
	 * @param status  the value for tbl_patient_diagnostic_habits1.STATUS
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.SORT_ORDER
	 * @return  the value of tbl_patient_diagnostic_habits1.SORT_ORDER
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.SORT_ORDER
	 * @param sortOrder  the value for tbl_patient_diagnostic_habits1.SORT_ORDER
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.INSERT_USER_ID
	 * @return  the value of tbl_patient_diagnostic_habits1.INSERT_USER_ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getInsertUserId() {
		return insertUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.INSERT_USER_ID
	 * @param insertUserId  the value for tbl_patient_diagnostic_habits1.INSERT_USER_ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setInsertUserId(String insertUserId) {
		this.insertUserId = insertUserId == null ? null : insertUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.INSERT_DATETIME
	 * @return  the value of tbl_patient_diagnostic_habits1.INSERT_DATETIME
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.INSERT_DATETIME
	 * @param insertDatetime  the value for tbl_patient_diagnostic_habits1.INSERT_DATETIME
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.UPDATE_USER_ID
	 * @return  the value of tbl_patient_diagnostic_habits1.UPDATE_USER_ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.UPDATE_USER_ID
	 * @param updateUserId  the value for tbl_patient_diagnostic_habits1.UPDATE_USER_ID
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId == null ? null : updateUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_diagnostic_habits1.UPDATE_DATETIME
	 * @return  the value of tbl_patient_diagnostic_habits1.UPDATE_DATETIME
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_diagnostic_habits1.UPDATE_DATETIME
	 * @param updateDatetime  the value for tbl_patient_diagnostic_habits1.UPDATE_DATETIME
	 * @mbg.generated  Mon May 07 10:49:26 IST 2018
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@Override
	public String toString() {
		return "PatientDiagnosticHabits1 [id=" + id + ", patientId=" + patientId + ", betelQuidIngredientsBetel="
				+ betelQuidIngredientsBetel + ", betelQuidIngredientsLime=" + betelQuidIngredientsLime
				+ ", betelQuidIngredientsTobacco=" + betelQuidIngredientsTobacco
				+ ", betelQuidIngredientsArecaProducts=" + betelQuidIngredientsArecaProducts
				+ ", betelQuidIngredientsArecanut=" + betelQuidIngredientsArecanut
				+ ", betelQuidIngredientsTobaccoProducts=" + betelQuidIngredientsTobaccoProducts
				+ ", betelQuidIngredientsOther=" + betelQuidIngredientsOther + ", betelQuidFrequency="
				+ betelQuidFrequency + ", betelQuidDuration=" + betelQuidDuration + ", smoking=" + smoking
				+ ", smokingCigarettes=" + smokingCigarettes + ", smokingCigarettesDuration="
				+ smokingCigarettesDuration + ", smokingCigarettesFrequency=" + smokingCigarettesFrequency
				+ ", smokingCigar=" + smokingCigar + ", smokingCigarDuration=" + smokingCigarDuration
				+ ", smokingCigarFrequency=" + smokingCigarFrequency + ", smokingBeedi=" + smokingBeedi
				+ ", smokingBeediDuration=" + smokingBeediDuration + ", smokingBeediFrequency=" + smokingBeediFrequency
				+ ", smokingPipe=" + smokingPipe + ", smokingPipeDuration=" + smokingPipeDuration
				+ ", smokingPipeFrequency=" + smokingPipeFrequency + ", smokingRollup=" + smokingRollup
				+ ", smokingRollupDuration=" + smokingRollupDuration + ", smokingRollupFrequency="
				+ smokingRollupFrequency + ", comment=" + comment + ", status=" + status + ", sortOrder=" + sortOrder
				+ ", insertUserId=" + insertUserId + ", insertDatetime=" + insertDatetime + ", updateUserId="
				+ updateUserId + ", updateDatetime=" + updateDatetime + "]";
	}
}