package com.doerit.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatientDiagnosticMedicalRecord2Example {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public PatientDiagnosticMedicalRecord2Example() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNull() {
			addCriterion("PATIENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNotNull() {
			addCriterion("PATIENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPatientIdEqualTo(String value) {
			addCriterion("PATIENT_ID =", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotEqualTo(String value) {
			addCriterion("PATIENT_ID <>", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThan(String value) {
			addCriterion("PATIENT_ID >", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID >=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThan(String value) {
			addCriterion("PATIENT_ID <", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID <=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLike(String value) {
			addCriterion("PATIENT_ID like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotLike(String value) {
			addCriterion("PATIENT_ID not like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdIn(List<String> values) {
			addCriterion("PATIENT_ID in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotIn(List<String> values) {
			addCriterion("PATIENT_ID not in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdBetween(String value1, String value2) {
			addCriterion("PATIENT_ID between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotBetween(String value1, String value2) {
			addCriterion("PATIENT_ID not between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaIsNull() {
			addCriterion("HEAMOPHILIA is null");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaIsNotNull() {
			addCriterion("HEAMOPHILIA is not null");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaEqualTo(String value) {
			addCriterion("HEAMOPHILIA =", value, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaNotEqualTo(String value) {
			addCriterion("HEAMOPHILIA <>", value, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaGreaterThan(String value) {
			addCriterion("HEAMOPHILIA >", value, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaGreaterThanOrEqualTo(String value) {
			addCriterion("HEAMOPHILIA >=", value, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaLessThan(String value) {
			addCriterion("HEAMOPHILIA <", value, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaLessThanOrEqualTo(String value) {
			addCriterion("HEAMOPHILIA <=", value, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaLike(String value) {
			addCriterion("HEAMOPHILIA like", value, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaNotLike(String value) {
			addCriterion("HEAMOPHILIA not like", value, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaIn(List<String> values) {
			addCriterion("HEAMOPHILIA in", values, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaNotIn(List<String> values) {
			addCriterion("HEAMOPHILIA not in", values, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaBetween(String value1, String value2) {
			addCriterion("HEAMOPHILIA between", value1, value2, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andHeamophiliaNotBetween(String value1, String value2) {
			addCriterion("HEAMOPHILIA not between", value1, value2, "heamophilia");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherIsNull() {
			addCriterion("BLEEDING_DISORDERS_OTHER is null");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherIsNotNull() {
			addCriterion("BLEEDING_DISORDERS_OTHER is not null");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherEqualTo(String value) {
			addCriterion("BLEEDING_DISORDERS_OTHER =", value, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherNotEqualTo(String value) {
			addCriterion("BLEEDING_DISORDERS_OTHER <>", value, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherGreaterThan(String value) {
			addCriterion("BLEEDING_DISORDERS_OTHER >", value, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherGreaterThanOrEqualTo(String value) {
			addCriterion("BLEEDING_DISORDERS_OTHER >=", value, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherLessThan(String value) {
			addCriterion("BLEEDING_DISORDERS_OTHER <", value, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherLessThanOrEqualTo(String value) {
			addCriterion("BLEEDING_DISORDERS_OTHER <=", value, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherLike(String value) {
			addCriterion("BLEEDING_DISORDERS_OTHER like", value, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherNotLike(String value) {
			addCriterion("BLEEDING_DISORDERS_OTHER not like", value, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherIn(List<String> values) {
			addCriterion("BLEEDING_DISORDERS_OTHER in", values, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherNotIn(List<String> values) {
			addCriterion("BLEEDING_DISORDERS_OTHER not in", values, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherBetween(String value1, String value2) {
			addCriterion("BLEEDING_DISORDERS_OTHER between", value1, value2, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andBleedingDisordersOtherNotBetween(String value1, String value2) {
			addCriterion("BLEEDING_DISORDERS_OTHER not between", value1, value2, "bleedingDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaIsNull() {
			addCriterion("CARDIAC_DISORDERS_ANGINA is null");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaIsNotNull() {
			addCriterion("CARDIAC_DISORDERS_ANGINA is not null");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_ANGINA =", value, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaNotEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_ANGINA <>", value, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaGreaterThan(String value) {
			addCriterion("CARDIAC_DISORDERS_ANGINA >", value, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaGreaterThanOrEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_ANGINA >=", value, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaLessThan(String value) {
			addCriterion("CARDIAC_DISORDERS_ANGINA <", value, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaLessThanOrEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_ANGINA <=", value, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaLike(String value) {
			addCriterion("CARDIAC_DISORDERS_ANGINA like", value, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaNotLike(String value) {
			addCriterion("CARDIAC_DISORDERS_ANGINA not like", value, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaIn(List<String> values) {
			addCriterion("CARDIAC_DISORDERS_ANGINA in", values, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaNotIn(List<String> values) {
			addCriterion("CARDIAC_DISORDERS_ANGINA not in", values, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaBetween(String value1, String value2) {
			addCriterion("CARDIAC_DISORDERS_ANGINA between", value1, value2, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersAnginaNotBetween(String value1, String value2) {
			addCriterion("CARDIAC_DISORDERS_ANGINA not between", value1, value2, "cardiacDisordersAngina");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularIsNull() {
			addCriterion("CARDIAC_DISORDERS_VALVULAR is null");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularIsNotNull() {
			addCriterion("CARDIAC_DISORDERS_VALVULAR is not null");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR =", value, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularNotEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR <>", value, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularGreaterThan(String value) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR >", value, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularGreaterThanOrEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR >=", value, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularLessThan(String value) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR <", value, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularLessThanOrEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR <=", value, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularLike(String value) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR like", value, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularNotLike(String value) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR not like", value, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularIn(List<String> values) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR in", values, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularNotIn(List<String> values) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR not in", values, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularBetween(String value1, String value2) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR between", value1, value2, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersValvularNotBetween(String value1, String value2) {
			addCriterion("CARDIAC_DISORDERS_VALVULAR not between", value1, value2, "cardiacDisordersValvular");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisIsNull() {
			addCriterion("CARDIAC_DISORDERS_CARDITIS is null");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisIsNotNull() {
			addCriterion("CARDIAC_DISORDERS_CARDITIS is not null");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS =", value, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisNotEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS <>", value, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisGreaterThan(String value) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS >", value, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisGreaterThanOrEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS >=", value, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisLessThan(String value) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS <", value, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisLessThanOrEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS <=", value, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisLike(String value) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS like", value, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisNotLike(String value) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS not like", value, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisIn(List<String> values) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS in", values, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisNotIn(List<String> values) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS not in", values, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisBetween(String value1, String value2) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS between", value1, value2, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersCarditisNotBetween(String value1, String value2) {
			addCriterion("CARDIAC_DISORDERS_CARDITIS not between", value1, value2, "cardiacDisordersCarditis");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherIsNull() {
			addCriterion("ANGINA_OTHER is null");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherIsNotNull() {
			addCriterion("ANGINA_OTHER is not null");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherEqualTo(String value) {
			addCriterion("ANGINA_OTHER =", value, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherNotEqualTo(String value) {
			addCriterion("ANGINA_OTHER <>", value, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherGreaterThan(String value) {
			addCriterion("ANGINA_OTHER >", value, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherGreaterThanOrEqualTo(String value) {
			addCriterion("ANGINA_OTHER >=", value, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherLessThan(String value) {
			addCriterion("ANGINA_OTHER <", value, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherLessThanOrEqualTo(String value) {
			addCriterion("ANGINA_OTHER <=", value, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherLike(String value) {
			addCriterion("ANGINA_OTHER like", value, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherNotLike(String value) {
			addCriterion("ANGINA_OTHER not like", value, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherIn(List<String> values) {
			addCriterion("ANGINA_OTHER in", values, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherNotIn(List<String> values) {
			addCriterion("ANGINA_OTHER not in", values, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherBetween(String value1, String value2) {
			addCriterion("ANGINA_OTHER between", value1, value2, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andAnginaOtherNotBetween(String value1, String value2) {
			addCriterion("ANGINA_OTHER not between", value1, value2, "anginaOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherIsNull() {
			addCriterion("VALVULAR_OTHER is null");
			return (Criteria) this;
		}

		public Criteria andValvularOtherIsNotNull() {
			addCriterion("VALVULAR_OTHER is not null");
			return (Criteria) this;
		}

		public Criteria andValvularOtherEqualTo(String value) {
			addCriterion("VALVULAR_OTHER =", value, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherNotEqualTo(String value) {
			addCriterion("VALVULAR_OTHER <>", value, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherGreaterThan(String value) {
			addCriterion("VALVULAR_OTHER >", value, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherGreaterThanOrEqualTo(String value) {
			addCriterion("VALVULAR_OTHER >=", value, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherLessThan(String value) {
			addCriterion("VALVULAR_OTHER <", value, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherLessThanOrEqualTo(String value) {
			addCriterion("VALVULAR_OTHER <=", value, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherLike(String value) {
			addCriterion("VALVULAR_OTHER like", value, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherNotLike(String value) {
			addCriterion("VALVULAR_OTHER not like", value, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherIn(List<String> values) {
			addCriterion("VALVULAR_OTHER in", values, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherNotIn(List<String> values) {
			addCriterion("VALVULAR_OTHER not in", values, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherBetween(String value1, String value2) {
			addCriterion("VALVULAR_OTHER between", value1, value2, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andValvularOtherNotBetween(String value1, String value2) {
			addCriterion("VALVULAR_OTHER not between", value1, value2, "valvularOther");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisIsNull() {
			addCriterion("SABE_PROPHYLAXIS is null");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisIsNotNull() {
			addCriterion("SABE_PROPHYLAXIS is not null");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisEqualTo(String value) {
			addCriterion("SABE_PROPHYLAXIS =", value, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisNotEqualTo(String value) {
			addCriterion("SABE_PROPHYLAXIS <>", value, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisGreaterThan(String value) {
			addCriterion("SABE_PROPHYLAXIS >", value, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisGreaterThanOrEqualTo(String value) {
			addCriterion("SABE_PROPHYLAXIS >=", value, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisLessThan(String value) {
			addCriterion("SABE_PROPHYLAXIS <", value, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisLessThanOrEqualTo(String value) {
			addCriterion("SABE_PROPHYLAXIS <=", value, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisLike(String value) {
			addCriterion("SABE_PROPHYLAXIS like", value, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisNotLike(String value) {
			addCriterion("SABE_PROPHYLAXIS not like", value, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisIn(List<String> values) {
			addCriterion("SABE_PROPHYLAXIS in", values, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisNotIn(List<String> values) {
			addCriterion("SABE_PROPHYLAXIS not in", values, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisBetween(String value1, String value2) {
			addCriterion("SABE_PROPHYLAXIS between", value1, value2, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andSabeProphylaxisNotBetween(String value1, String value2) {
			addCriterion("SABE_PROPHYLAXIS not between", value1, value2, "sabeProphylaxis");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinIsNull() {
			addCriterion("ORAL_PENICILLIN is null");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinIsNotNull() {
			addCriterion("ORAL_PENICILLIN is not null");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinEqualTo(String value) {
			addCriterion("ORAL_PENICILLIN =", value, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinNotEqualTo(String value) {
			addCriterion("ORAL_PENICILLIN <>", value, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinGreaterThan(String value) {
			addCriterion("ORAL_PENICILLIN >", value, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinGreaterThanOrEqualTo(String value) {
			addCriterion("ORAL_PENICILLIN >=", value, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinLessThan(String value) {
			addCriterion("ORAL_PENICILLIN <", value, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinLessThanOrEqualTo(String value) {
			addCriterion("ORAL_PENICILLIN <=", value, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinLike(String value) {
			addCriterion("ORAL_PENICILLIN like", value, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinNotLike(String value) {
			addCriterion("ORAL_PENICILLIN not like", value, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinIn(List<String> values) {
			addCriterion("ORAL_PENICILLIN in", values, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinNotIn(List<String> values) {
			addCriterion("ORAL_PENICILLIN not in", values, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinBetween(String value1, String value2) {
			addCriterion("ORAL_PENICILLIN between", value1, value2, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andOralPenicillinNotBetween(String value1, String value2) {
			addCriterion("ORAL_PENICILLIN not between", value1, value2, "oralPenicillin");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveIsNull() {
			addCriterion("PROSTHETIC_HEART_VALVE is null");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveIsNotNull() {
			addCriterion("PROSTHETIC_HEART_VALVE is not null");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveEqualTo(String value) {
			addCriterion("PROSTHETIC_HEART_VALVE =", value, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveNotEqualTo(String value) {
			addCriterion("PROSTHETIC_HEART_VALVE <>", value, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveGreaterThan(String value) {
			addCriterion("PROSTHETIC_HEART_VALVE >", value, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveGreaterThanOrEqualTo(String value) {
			addCriterion("PROSTHETIC_HEART_VALVE >=", value, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveLessThan(String value) {
			addCriterion("PROSTHETIC_HEART_VALVE <", value, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveLessThanOrEqualTo(String value) {
			addCriterion("PROSTHETIC_HEART_VALVE <=", value, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveLike(String value) {
			addCriterion("PROSTHETIC_HEART_VALVE like", value, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveNotLike(String value) {
			addCriterion("PROSTHETIC_HEART_VALVE not like", value, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveIn(List<String> values) {
			addCriterion("PROSTHETIC_HEART_VALVE in", values, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveNotIn(List<String> values) {
			addCriterion("PROSTHETIC_HEART_VALVE not in", values, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveBetween(String value1, String value2) {
			addCriterion("PROSTHETIC_HEART_VALVE between", value1, value2, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andProstheticHeartValveNotBetween(String value1, String value2) {
			addCriterion("PROSTHETIC_HEART_VALVE not between", value1, value2, "prostheticHeartValve");
			return (Criteria) this;
		}

		public Criteria andPacemakerIsNull() {
			addCriterion("PACEMAKER is null");
			return (Criteria) this;
		}

		public Criteria andPacemakerIsNotNull() {
			addCriterion("PACEMAKER is not null");
			return (Criteria) this;
		}

		public Criteria andPacemakerEqualTo(String value) {
			addCriterion("PACEMAKER =", value, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerNotEqualTo(String value) {
			addCriterion("PACEMAKER <>", value, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerGreaterThan(String value) {
			addCriterion("PACEMAKER >", value, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerGreaterThanOrEqualTo(String value) {
			addCriterion("PACEMAKER >=", value, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerLessThan(String value) {
			addCriterion("PACEMAKER <", value, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerLessThanOrEqualTo(String value) {
			addCriterion("PACEMAKER <=", value, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerLike(String value) {
			addCriterion("PACEMAKER like", value, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerNotLike(String value) {
			addCriterion("PACEMAKER not like", value, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerIn(List<String> values) {
			addCriterion("PACEMAKER in", values, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerNotIn(List<String> values) {
			addCriterion("PACEMAKER not in", values, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerBetween(String value1, String value2) {
			addCriterion("PACEMAKER between", value1, value2, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andPacemakerNotBetween(String value1, String value2) {
			addCriterion("PACEMAKER not between", value1, value2, "pacemaker");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherIsNull() {
			addCriterion("CARDIAC_DISORDERS_OTHER is null");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherIsNotNull() {
			addCriterion("CARDIAC_DISORDERS_OTHER is not null");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_OTHER =", value, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherNotEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_OTHER <>", value, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherGreaterThan(String value) {
			addCriterion("CARDIAC_DISORDERS_OTHER >", value, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherGreaterThanOrEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_OTHER >=", value, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherLessThan(String value) {
			addCriterion("CARDIAC_DISORDERS_OTHER <", value, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherLessThanOrEqualTo(String value) {
			addCriterion("CARDIAC_DISORDERS_OTHER <=", value, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherLike(String value) {
			addCriterion("CARDIAC_DISORDERS_OTHER like", value, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherNotLike(String value) {
			addCriterion("CARDIAC_DISORDERS_OTHER not like", value, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherIn(List<String> values) {
			addCriterion("CARDIAC_DISORDERS_OTHER in", values, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherNotIn(List<String> values) {
			addCriterion("CARDIAC_DISORDERS_OTHER not in", values, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherBetween(String value1, String value2) {
			addCriterion("CARDIAC_DISORDERS_OTHER between", value1, value2, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andCardiacDisordersOtherNotBetween(String value1, String value2) {
			addCriterion("CARDIAC_DISORDERS_OTHER not between", value1, value2, "cardiacDisordersOther");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipIsNull() {
			addCriterion("DEVELOPMENTAL_CLEFTLIP is null");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipIsNotNull() {
			addCriterion("DEVELOPMENTAL_CLEFTLIP is not null");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP =", value, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipNotEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP <>", value, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipGreaterThan(String value) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP >", value, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipGreaterThanOrEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP >=", value, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipLessThan(String value) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP <", value, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipLessThanOrEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP <=", value, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipLike(String value) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP like", value, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipNotLike(String value) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP not like", value, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipIn(List<String> values) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP in", values, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipNotIn(List<String> values) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP not in", values, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipBetween(String value1, String value2) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP between", value1, value2, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCleftlipNotBetween(String value1, String value2) {
			addCriterion("DEVELOPMENTAL_CLEFTLIP not between", value1, value2, "developmentalCleftlip");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralIsNull() {
			addCriterion("DEVELOPMENTAL_CEREBRAL is null");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralIsNotNull() {
			addCriterion("DEVELOPMENTAL_CEREBRAL is not null");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_CEREBRAL =", value, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralNotEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_CEREBRAL <>", value, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralGreaterThan(String value) {
			addCriterion("DEVELOPMENTAL_CEREBRAL >", value, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralGreaterThanOrEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_CEREBRAL >=", value, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralLessThan(String value) {
			addCriterion("DEVELOPMENTAL_CEREBRAL <", value, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralLessThanOrEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_CEREBRAL <=", value, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralLike(String value) {
			addCriterion("DEVELOPMENTAL_CEREBRAL like", value, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralNotLike(String value) {
			addCriterion("DEVELOPMENTAL_CEREBRAL not like", value, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralIn(List<String> values) {
			addCriterion("DEVELOPMENTAL_CEREBRAL in", values, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralNotIn(List<String> values) {
			addCriterion("DEVELOPMENTAL_CEREBRAL not in", values, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralBetween(String value1, String value2) {
			addCriterion("DEVELOPMENTAL_CEREBRAL between", value1, value2, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalCerebralNotBetween(String value1, String value2) {
			addCriterion("DEVELOPMENTAL_CEREBRAL not between", value1, value2, "developmentalCerebral");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicIsNull() {
			addCriterion("DEVELOPMENTAL_SYNDROMIC is null");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicIsNotNull() {
			addCriterion("DEVELOPMENTAL_SYNDROMIC is not null");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC =", value, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicNotEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC <>", value, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicGreaterThan(String value) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC >", value, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicGreaterThanOrEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC >=", value, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicLessThan(String value) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC <", value, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicLessThanOrEqualTo(String value) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC <=", value, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicLike(String value) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC like", value, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicNotLike(String value) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC not like", value, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicIn(List<String> values) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC in", values, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicNotIn(List<String> values) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC not in", values, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicBetween(String value1, String value2) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC between", value1, value2, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andDevelopmentalSyndromicNotBetween(String value1, String value2) {
			addCriterion("DEVELOPMENTAL_SYNDROMIC not between", value1, value2, "developmentalSyndromic");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesIsNull() {
			addCriterion("ENDOCRINE_DIABETES is null");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesIsNotNull() {
			addCriterion("ENDOCRINE_DIABETES is not null");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesEqualTo(String value) {
			addCriterion("ENDOCRINE_DIABETES =", value, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesNotEqualTo(String value) {
			addCriterion("ENDOCRINE_DIABETES <>", value, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesGreaterThan(String value) {
			addCriterion("ENDOCRINE_DIABETES >", value, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesGreaterThanOrEqualTo(String value) {
			addCriterion("ENDOCRINE_DIABETES >=", value, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesLessThan(String value) {
			addCriterion("ENDOCRINE_DIABETES <", value, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesLessThanOrEqualTo(String value) {
			addCriterion("ENDOCRINE_DIABETES <=", value, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesLike(String value) {
			addCriterion("ENDOCRINE_DIABETES like", value, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesNotLike(String value) {
			addCriterion("ENDOCRINE_DIABETES not like", value, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesIn(List<String> values) {
			addCriterion("ENDOCRINE_DIABETES in", values, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesNotIn(List<String> values) {
			addCriterion("ENDOCRINE_DIABETES not in", values, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesBetween(String value1, String value2) {
			addCriterion("ENDOCRINE_DIABETES between", value1, value2, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineDiabetesNotBetween(String value1, String value2) {
			addCriterion("ENDOCRINE_DIABETES not between", value1, value2, "endocrineDiabetes");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherIsNull() {
			addCriterion("ENDOCRINE_OTHER is null");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherIsNotNull() {
			addCriterion("ENDOCRINE_OTHER is not null");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherEqualTo(String value) {
			addCriterion("ENDOCRINE_OTHER =", value, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherNotEqualTo(String value) {
			addCriterion("ENDOCRINE_OTHER <>", value, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherGreaterThan(String value) {
			addCriterion("ENDOCRINE_OTHER >", value, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherGreaterThanOrEqualTo(String value) {
			addCriterion("ENDOCRINE_OTHER >=", value, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherLessThan(String value) {
			addCriterion("ENDOCRINE_OTHER <", value, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherLessThanOrEqualTo(String value) {
			addCriterion("ENDOCRINE_OTHER <=", value, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherLike(String value) {
			addCriterion("ENDOCRINE_OTHER like", value, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherNotLike(String value) {
			addCriterion("ENDOCRINE_OTHER not like", value, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherIn(List<String> values) {
			addCriterion("ENDOCRINE_OTHER in", values, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherNotIn(List<String> values) {
			addCriterion("ENDOCRINE_OTHER not in", values, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherBetween(String value1, String value2) {
			addCriterion("ENDOCRINE_OTHER between", value1, value2, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherNotBetween(String value1, String value2) {
			addCriterion("ENDOCRINE_OTHER not between", value1, value2, "endocrineOther");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsIsNull() {
			addCriterion("ENDOCRINE_OTHER_COMMENTS is null");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsIsNotNull() {
			addCriterion("ENDOCRINE_OTHER_COMMENTS is not null");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsEqualTo(String value) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS =", value, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsNotEqualTo(String value) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS <>", value, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsGreaterThan(String value) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS >", value, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsGreaterThanOrEqualTo(String value) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS >=", value, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsLessThan(String value) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS <", value, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsLessThanOrEqualTo(String value) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS <=", value, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsLike(String value) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS like", value, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsNotLike(String value) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS not like", value, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsIn(List<String> values) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS in", values, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsNotIn(List<String> values) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS not in", values, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsBetween(String value1, String value2) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS between", value1, value2, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEndocrineOtherCommentsNotBetween(String value1, String value2) {
			addCriterion("ENDOCRINE_OTHER_COMMENTS not between", value1, value2, "endocrineOtherComments");
			return (Criteria) this;
		}

		public Criteria andEpilepsyIsNull() {
			addCriterion("EPILEPSY is null");
			return (Criteria) this;
		}

		public Criteria andEpilepsyIsNotNull() {
			addCriterion("EPILEPSY is not null");
			return (Criteria) this;
		}

		public Criteria andEpilepsyEqualTo(String value) {
			addCriterion("EPILEPSY =", value, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyNotEqualTo(String value) {
			addCriterion("EPILEPSY <>", value, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyGreaterThan(String value) {
			addCriterion("EPILEPSY >", value, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyGreaterThanOrEqualTo(String value) {
			addCriterion("EPILEPSY >=", value, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyLessThan(String value) {
			addCriterion("EPILEPSY <", value, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyLessThanOrEqualTo(String value) {
			addCriterion("EPILEPSY <=", value, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyLike(String value) {
			addCriterion("EPILEPSY like", value, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyNotLike(String value) {
			addCriterion("EPILEPSY not like", value, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyIn(List<String> values) {
			addCriterion("EPILEPSY in", values, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyNotIn(List<String> values) {
			addCriterion("EPILEPSY not in", values, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyBetween(String value1, String value2) {
			addCriterion("EPILEPSY between", value1, value2, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andEpilepsyNotBetween(String value1, String value2) {
			addCriterion("EPILEPSY not between", value1, value2, "epilepsy");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("COMMENT is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("COMMENT is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("COMMENT =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("COMMENT <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("COMMENT >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("COMMENT >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("COMMENT <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("COMMENT <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("COMMENT like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("COMMENT not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("COMMENT in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("COMMENT not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("COMMENT between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("COMMENT not between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNull() {
			addCriterion("SORT_ORDER is null");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNotNull() {
			addCriterion("SORT_ORDER is not null");
			return (Criteria) this;
		}

		public Criteria andSortOrderEqualTo(Integer value) {
			addCriterion("SORT_ORDER =", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotEqualTo(Integer value) {
			addCriterion("SORT_ORDER <>", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThan(Integer value) {
			addCriterion("SORT_ORDER >", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER >=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThan(Integer value) {
			addCriterion("SORT_ORDER <", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER <=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderIn(List<Integer> values) {
			addCriterion("SORT_ORDER in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotIn(List<Integer> values) {
			addCriterion("SORT_ORDER not in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER not between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNull() {
			addCriterion("INSERT_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNotNull() {
			addCriterion("INSERT_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdEqualTo(String value) {
			addCriterion("INSERT_USER_ID =", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotEqualTo(String value) {
			addCriterion("INSERT_USER_ID <>", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThan(String value) {
			addCriterion("INSERT_USER_ID >", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID >=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThan(String value) {
			addCriterion("INSERT_USER_ID <", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID <=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLike(String value) {
			addCriterion("INSERT_USER_ID like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotLike(String value) {
			addCriterion("INSERT_USER_ID not like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIn(List<String> values) {
			addCriterion("INSERT_USER_ID in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotIn(List<String> values) {
			addCriterion("INSERT_USER_ID not in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID not between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("INSERT_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("INSERT_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("INSERT_DATETIME =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("INSERT_DATETIME >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("INSERT_DATETIME <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("INSERT_DATETIME in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("INSERT_DATETIME not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNull() {
			addCriterion("UPDATE_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNotNull() {
			addCriterion("UPDATE_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdEqualTo(String value) {
			addCriterion("UPDATE_USER_ID =", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThan(String value) {
			addCriterion("UPDATE_USER_ID >", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThan(String value) {
			addCriterion("UPDATE_USER_ID <", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLike(String value) {
			addCriterion("UPDATE_USER_ID like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotLike(String value) {
			addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIn(List<String> values) {
			addCriterion("UPDATE_USER_ID in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotIn(List<String> values) {
			addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("UPDATE_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("UPDATE_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("UPDATE_DATETIME >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("UPDATE_DATETIME <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_diagnostic_medicalrecord2
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 22 14:46:49 IST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}