package com.doerit.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatientRequestConebeamExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public PatientRequestConebeamExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNull() {
			addCriterion("PATIENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNotNull() {
			addCriterion("PATIENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPatientIdEqualTo(String value) {
			addCriterion("PATIENT_ID =", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotEqualTo(String value) {
			addCriterion("PATIENT_ID <>", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThan(String value) {
			addCriterion("PATIENT_ID >", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID >=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThan(String value) {
			addCriterion("PATIENT_ID <", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID <=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLike(String value) {
			addCriterion("PATIENT_ID like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotLike(String value) {
			addCriterion("PATIENT_ID not like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdIn(List<String> values) {
			addCriterion("PATIENT_ID in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotIn(List<String> values) {
			addCriterion("PATIENT_ID not in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdBetween(String value1, String value2) {
			addCriterion("PATIENT_ID between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotBetween(String value1, String value2) {
			addCriterion("PATIENT_ID not between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andUrgentIsNull() {
			addCriterion("URGENT is null");
			return (Criteria) this;
		}

		public Criteria andUrgentIsNotNull() {
			addCriterion("URGENT is not null");
			return (Criteria) this;
		}

		public Criteria andUrgentEqualTo(String value) {
			addCriterion("URGENT =", value, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentNotEqualTo(String value) {
			addCriterion("URGENT <>", value, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentGreaterThan(String value) {
			addCriterion("URGENT >", value, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentGreaterThanOrEqualTo(String value) {
			addCriterion("URGENT >=", value, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentLessThan(String value) {
			addCriterion("URGENT <", value, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentLessThanOrEqualTo(String value) {
			addCriterion("URGENT <=", value, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentLike(String value) {
			addCriterion("URGENT like", value, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentNotLike(String value) {
			addCriterion("URGENT not like", value, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentIn(List<String> values) {
			addCriterion("URGENT in", values, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentNotIn(List<String> values) {
			addCriterion("URGENT not in", values, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentBetween(String value1, String value2) {
			addCriterion("URGENT between", value1, value2, "urgent");
			return (Criteria) this;
		}

		public Criteria andUrgentNotBetween(String value1, String value2) {
			addCriterion("URGENT not between", value1, value2, "urgent");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoIsNull() {
			addCriterion("PREVIOUS_XRAY_INFO is null");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoIsNotNull() {
			addCriterion("PREVIOUS_XRAY_INFO is not null");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoEqualTo(String value) {
			addCriterion("PREVIOUS_XRAY_INFO =", value, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoNotEqualTo(String value) {
			addCriterion("PREVIOUS_XRAY_INFO <>", value, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoGreaterThan(String value) {
			addCriterion("PREVIOUS_XRAY_INFO >", value, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoGreaterThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_XRAY_INFO >=", value, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoLessThan(String value) {
			addCriterion("PREVIOUS_XRAY_INFO <", value, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoLessThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_XRAY_INFO <=", value, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoLike(String value) {
			addCriterion("PREVIOUS_XRAY_INFO like", value, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoNotLike(String value) {
			addCriterion("PREVIOUS_XRAY_INFO not like", value, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoIn(List<String> values) {
			addCriterion("PREVIOUS_XRAY_INFO in", values, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoNotIn(List<String> values) {
			addCriterion("PREVIOUS_XRAY_INFO not in", values, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoBetween(String value1, String value2) {
			addCriterion("PREVIOUS_XRAY_INFO between", value1, value2, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andPreviousXrayInfoNotBetween(String value1, String value2) {
			addCriterion("PREVIOUS_XRAY_INFO not between", value1, value2, "previousXrayInfo");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteIsNull() {
			addCriterion("CLINICAL_NOTE is null");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteIsNotNull() {
			addCriterion("CLINICAL_NOTE is not null");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteEqualTo(String value) {
			addCriterion("CLINICAL_NOTE =", value, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteNotEqualTo(String value) {
			addCriterion("CLINICAL_NOTE <>", value, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteGreaterThan(String value) {
			addCriterion("CLINICAL_NOTE >", value, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteGreaterThanOrEqualTo(String value) {
			addCriterion("CLINICAL_NOTE >=", value, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteLessThan(String value) {
			addCriterion("CLINICAL_NOTE <", value, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteLessThanOrEqualTo(String value) {
			addCriterion("CLINICAL_NOTE <=", value, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteLike(String value) {
			addCriterion("CLINICAL_NOTE like", value, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteNotLike(String value) {
			addCriterion("CLINICAL_NOTE not like", value, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteIn(List<String> values) {
			addCriterion("CLINICAL_NOTE in", values, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteNotIn(List<String> values) {
			addCriterion("CLINICAL_NOTE not in", values, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteBetween(String value1, String value2) {
			addCriterion("CLINICAL_NOTE between", value1, value2, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andClinicalNoteNotBetween(String value1, String value2) {
			addCriterion("CLINICAL_NOTE not between", value1, value2, "clinicalNote");
			return (Criteria) this;
		}

		public Criteria andConsultantNameIsNull() {
			addCriterion("CONSULTANT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andConsultantNameIsNotNull() {
			addCriterion("CONSULTANT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andConsultantNameEqualTo(String value) {
			addCriterion("CONSULTANT_NAME =", value, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameNotEqualTo(String value) {
			addCriterion("CONSULTANT_NAME <>", value, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameGreaterThan(String value) {
			addCriterion("CONSULTANT_NAME >", value, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameGreaterThanOrEqualTo(String value) {
			addCriterion("CONSULTANT_NAME >=", value, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameLessThan(String value) {
			addCriterion("CONSULTANT_NAME <", value, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameLessThanOrEqualTo(String value) {
			addCriterion("CONSULTANT_NAME <=", value, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameLike(String value) {
			addCriterion("CONSULTANT_NAME like", value, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameNotLike(String value) {
			addCriterion("CONSULTANT_NAME not like", value, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameIn(List<String> values) {
			addCriterion("CONSULTANT_NAME in", values, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameNotIn(List<String> values) {
			addCriterion("CONSULTANT_NAME not in", values, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameBetween(String value1, String value2) {
			addCriterion("CONSULTANT_NAME between", value1, value2, "consultantName");
			return (Criteria) this;
		}

		public Criteria andConsultantNameNotBetween(String value1, String value2) {
			addCriterion("CONSULTANT_NAME not between", value1, value2, "consultantName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameIsNull() {
			addCriterion("HOSPITAL_NAME is null");
			return (Criteria) this;
		}

		public Criteria andHospitalNameIsNotNull() {
			addCriterion("HOSPITAL_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andHospitalNameEqualTo(String value) {
			addCriterion("HOSPITAL_NAME =", value, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameNotEqualTo(String value) {
			addCriterion("HOSPITAL_NAME <>", value, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameGreaterThan(String value) {
			addCriterion("HOSPITAL_NAME >", value, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameGreaterThanOrEqualTo(String value) {
			addCriterion("HOSPITAL_NAME >=", value, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameLessThan(String value) {
			addCriterion("HOSPITAL_NAME <", value, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameLessThanOrEqualTo(String value) {
			addCriterion("HOSPITAL_NAME <=", value, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameLike(String value) {
			addCriterion("HOSPITAL_NAME like", value, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameNotLike(String value) {
			addCriterion("HOSPITAL_NAME not like", value, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameIn(List<String> values) {
			addCriterion("HOSPITAL_NAME in", values, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameNotIn(List<String> values) {
			addCriterion("HOSPITAL_NAME not in", values, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameBetween(String value1, String value2) {
			addCriterion("HOSPITAL_NAME between", value1, value2, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andHospitalNameNotBetween(String value1, String value2) {
			addCriterion("HOSPITAL_NAME not between", value1, value2, "hospitalName");
			return (Criteria) this;
		}

		public Criteria andConsultantSignIsNull() {
			addCriterion("CONSULTANT_SIGN is null");
			return (Criteria) this;
		}

		public Criteria andConsultantSignIsNotNull() {
			addCriterion("CONSULTANT_SIGN is not null");
			return (Criteria) this;
		}

		public Criteria andConsultantSignEqualTo(String value) {
			addCriterion("CONSULTANT_SIGN =", value, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignNotEqualTo(String value) {
			addCriterion("CONSULTANT_SIGN <>", value, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignGreaterThan(String value) {
			addCriterion("CONSULTANT_SIGN >", value, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignGreaterThanOrEqualTo(String value) {
			addCriterion("CONSULTANT_SIGN >=", value, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignLessThan(String value) {
			addCriterion("CONSULTANT_SIGN <", value, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignLessThanOrEqualTo(String value) {
			addCriterion("CONSULTANT_SIGN <=", value, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignLike(String value) {
			addCriterion("CONSULTANT_SIGN like", value, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignNotLike(String value) {
			addCriterion("CONSULTANT_SIGN not like", value, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignIn(List<String> values) {
			addCriterion("CONSULTANT_SIGN in", values, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignNotIn(List<String> values) {
			addCriterion("CONSULTANT_SIGN not in", values, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignBetween(String value1, String value2) {
			addCriterion("CONSULTANT_SIGN between", value1, value2, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andConsultantSignNotBetween(String value1, String value2) {
			addCriterion("CONSULTANT_SIGN not between", value1, value2, "consultantSign");
			return (Criteria) this;
		}

		public Criteria andDateRequestedIsNull() {
			addCriterion("DATE_REQUESTED is null");
			return (Criteria) this;
		}

		public Criteria andDateRequestedIsNotNull() {
			addCriterion("DATE_REQUESTED is not null");
			return (Criteria) this;
		}

		public Criteria andDateRequestedEqualTo(Date value) {
			addCriterion("DATE_REQUESTED =", value, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateRequestedNotEqualTo(Date value) {
			addCriterion("DATE_REQUESTED <>", value, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateRequestedGreaterThan(Date value) {
			addCriterion("DATE_REQUESTED >", value, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateRequestedGreaterThanOrEqualTo(Date value) {
			addCriterion("DATE_REQUESTED >=", value, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateRequestedLessThan(Date value) {
			addCriterion("DATE_REQUESTED <", value, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateRequestedLessThanOrEqualTo(Date value) {
			addCriterion("DATE_REQUESTED <=", value, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateRequestedIn(List<Date> values) {
			addCriterion("DATE_REQUESTED in", values, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateRequestedNotIn(List<Date> values) {
			addCriterion("DATE_REQUESTED not in", values, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateRequestedBetween(Date value1, Date value2) {
			addCriterion("DATE_REQUESTED between", value1, value2, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateRequestedNotBetween(Date value1, Date value2) {
			addCriterion("DATE_REQUESTED not between", value1, value2, "dateRequested");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentIsNull() {
			addCriterion("DATE_APPOINTMENT is null");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentIsNotNull() {
			addCriterion("DATE_APPOINTMENT is not null");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentEqualTo(Date value) {
			addCriterion("DATE_APPOINTMENT =", value, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentNotEqualTo(Date value) {
			addCriterion("DATE_APPOINTMENT <>", value, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentGreaterThan(Date value) {
			addCriterion("DATE_APPOINTMENT >", value, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentGreaterThanOrEqualTo(Date value) {
			addCriterion("DATE_APPOINTMENT >=", value, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentLessThan(Date value) {
			addCriterion("DATE_APPOINTMENT <", value, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentLessThanOrEqualTo(Date value) {
			addCriterion("DATE_APPOINTMENT <=", value, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentIn(List<Date> values) {
			addCriterion("DATE_APPOINTMENT in", values, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentNotIn(List<Date> values) {
			addCriterion("DATE_APPOINTMENT not in", values, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentBetween(Date value1, Date value2) {
			addCriterion("DATE_APPOINTMENT between", value1, value2, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andDateAppointmentNotBetween(Date value1, Date value2) {
			addCriterion("DATE_APPOINTMENT not between", value1, value2, "dateAppointment");
			return (Criteria) this;
		}

		public Criteria andCdGivenIsNull() {
			addCriterion("CD_GIVEN is null");
			return (Criteria) this;
		}

		public Criteria andCdGivenIsNotNull() {
			addCriterion("CD_GIVEN is not null");
			return (Criteria) this;
		}

		public Criteria andCdGivenEqualTo(String value) {
			addCriterion("CD_GIVEN =", value, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenNotEqualTo(String value) {
			addCriterion("CD_GIVEN <>", value, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenGreaterThan(String value) {
			addCriterion("CD_GIVEN >", value, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenGreaterThanOrEqualTo(String value) {
			addCriterion("CD_GIVEN >=", value, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenLessThan(String value) {
			addCriterion("CD_GIVEN <", value, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenLessThanOrEqualTo(String value) {
			addCriterion("CD_GIVEN <=", value, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenLike(String value) {
			addCriterion("CD_GIVEN like", value, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenNotLike(String value) {
			addCriterion("CD_GIVEN not like", value, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenIn(List<String> values) {
			addCriterion("CD_GIVEN in", values, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenNotIn(List<String> values) {
			addCriterion("CD_GIVEN not in", values, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenBetween(String value1, String value2) {
			addCriterion("CD_GIVEN between", value1, value2, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andCdGivenNotBetween(String value1, String value2) {
			addCriterion("CD_GIVEN not between", value1, value2, "cdGiven");
			return (Criteria) this;
		}

		public Criteria andPropertyValueIsNull() {
			addCriterion("PROPERTY_VALUE is null");
			return (Criteria) this;
		}

		public Criteria andPropertyValueIsNotNull() {
			addCriterion("PROPERTY_VALUE is not null");
			return (Criteria) this;
		}

		public Criteria andPropertyValueEqualTo(String value) {
			addCriterion("PROPERTY_VALUE =", value, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueNotEqualTo(String value) {
			addCriterion("PROPERTY_VALUE <>", value, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueGreaterThan(String value) {
			addCriterion("PROPERTY_VALUE >", value, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueGreaterThanOrEqualTo(String value) {
			addCriterion("PROPERTY_VALUE >=", value, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueLessThan(String value) {
			addCriterion("PROPERTY_VALUE <", value, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueLessThanOrEqualTo(String value) {
			addCriterion("PROPERTY_VALUE <=", value, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueLike(String value) {
			addCriterion("PROPERTY_VALUE like", value, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueNotLike(String value) {
			addCriterion("PROPERTY_VALUE not like", value, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueIn(List<String> values) {
			addCriterion("PROPERTY_VALUE in", values, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueNotIn(List<String> values) {
			addCriterion("PROPERTY_VALUE not in", values, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueBetween(String value1, String value2) {
			addCriterion("PROPERTY_VALUE between", value1, value2, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andPropertyValueNotBetween(String value1, String value2) {
			addCriterion("PROPERTY_VALUE not between", value1, value2, "propertyValue");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("COMMENT is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("COMMENT is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("COMMENT =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("COMMENT <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("COMMENT >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("COMMENT >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("COMMENT <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("COMMENT <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("COMMENT like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("COMMENT not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("COMMENT in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("COMMENT not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("COMMENT between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("COMMENT not between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNull() {
			addCriterion("SORT_ORDER is null");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNotNull() {
			addCriterion("SORT_ORDER is not null");
			return (Criteria) this;
		}

		public Criteria andSortOrderEqualTo(Integer value) {
			addCriterion("SORT_ORDER =", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotEqualTo(Integer value) {
			addCriterion("SORT_ORDER <>", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThan(Integer value) {
			addCriterion("SORT_ORDER >", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER >=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThan(Integer value) {
			addCriterion("SORT_ORDER <", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER <=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderIn(List<Integer> values) {
			addCriterion("SORT_ORDER in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotIn(List<Integer> values) {
			addCriterion("SORT_ORDER not in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER not between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNull() {
			addCriterion("INSERT_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNotNull() {
			addCriterion("INSERT_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdEqualTo(String value) {
			addCriterion("INSERT_USER_ID =", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotEqualTo(String value) {
			addCriterion("INSERT_USER_ID <>", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThan(String value) {
			addCriterion("INSERT_USER_ID >", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID >=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThan(String value) {
			addCriterion("INSERT_USER_ID <", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID <=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLike(String value) {
			addCriterion("INSERT_USER_ID like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotLike(String value) {
			addCriterion("INSERT_USER_ID not like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIn(List<String> values) {
			addCriterion("INSERT_USER_ID in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotIn(List<String> values) {
			addCriterion("INSERT_USER_ID not in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID not between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNull() {
			addCriterion("UPDATE_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNotNull() {
			addCriterion("UPDATE_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdEqualTo(String value) {
			addCriterion("UPDATE_USER_ID =", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThan(String value) {
			addCriterion("UPDATE_USER_ID >", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThan(String value) {
			addCriterion("UPDATE_USER_ID <", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLike(String value) {
			addCriterion("UPDATE_USER_ID like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotLike(String value) {
			addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIn(List<String> values) {
			addCriterion("UPDATE_USER_ID in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotIn(List<String> values) {
			addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("INSERT_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("INSERT_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("INSERT_DATETIME =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("INSERT_DATETIME >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("INSERT_DATETIME <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("INSERT_DATETIME in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("INSERT_DATETIME not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("UPDATE_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("UPDATE_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("UPDATE_DATETIME >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("UPDATE_DATETIME <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_request_conebeam
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_request_conebeam
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 13 22:08:32 IST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}