package com.doerit.model;

import java.util.Date;

public class PatientDiagnosticBrushingHabits implements InsertUpdate {
    @Override
	public String toString() {
		return "PatientDiagnosticBrushingHabits [id=" + id + ", patientId=" + patientId + ", brushingTool="
				+ brushingTool + ", brushingToolOther=" + brushingToolOther + ", toothpaste=" + toothpaste
				+ ", toothpasteOther=" + toothpasteOther + ", brushingFrequency=" + brushingFrequency + ", bristles="
				+ bristles + ", brushingDuration=" + brushingDuration + ", supplementNone=" + supplementNone
				+ ", supplementFloss=" + supplementFloss + ", supplementBottleBrushes=" + supplementBottleBrushes
				+ ", supplementSingleTuft=" + supplementSingleTuft + ", supplementWoodpicks=" + supplementWoodpicks
				+ ", supplementIrrigators=" + supplementIrrigators + ", supplementOther=" + supplementOther
				+ ", comment=" + comment + ", status=" + status + ", sortOrder=" + sortOrder + ", insertUserId="
				+ insertUserId + ", insertDatetime=" + insertDatetime + ", updateUserId=" + updateUserId
				+ ", updateDatetime=" + updateDatetime + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.PATIENT_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String brushingTool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL_OTHER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String brushingToolOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.TOOTHPASTE
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String toothpaste;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.TOOTHPASTE_OTHER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String toothpasteOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_FREQUENCY
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String brushingFrequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.BRISTLES
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String bristles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_DURATION
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String brushingDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_NONE
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String supplementNone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_FLOSS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String supplementFloss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_BOTTLE_BRUSHES
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String supplementBottleBrushes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_SINGLE_TUFT
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String supplementSingleTuft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_WOODPICKS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String supplementWoodpicks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_IRRIGATORS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String supplementIrrigators;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_OTHER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String supplementOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.COMMENT
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.STATUS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.SORT_ORDER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.INSERT_USER_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.INSERT_DATETIME
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private Date insertDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.UPDATE_USER_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_diagnostic_brushing_habits.UPDATE_DATETIME
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.ID
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.ID
     *
     * @param id the value for tbl_patient_diagnostic_brushing_habits.ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.PATIENT_ID
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.PATIENT_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.PATIENT_ID
     *
     * @param patientId the value for tbl_patient_diagnostic_brushing_habits.PATIENT_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getBrushingTool() {
        return brushingTool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL
     *
     * @param brushingTool the value for tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setBrushingTool(String brushingTool) {
        this.brushingTool = brushingTool == null ? null : brushingTool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL_OTHER
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL_OTHER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getBrushingToolOther() {
        return brushingToolOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL_OTHER
     *
     * @param brushingToolOther the value for tbl_patient_diagnostic_brushing_habits.BRUSHING_TOOL_OTHER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setBrushingToolOther(String brushingToolOther) {
        this.brushingToolOther = brushingToolOther == null ? null : brushingToolOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.TOOTHPASTE
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.TOOTHPASTE
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getToothpaste() {
        return toothpaste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.TOOTHPASTE
     *
     * @param toothpaste the value for tbl_patient_diagnostic_brushing_habits.TOOTHPASTE
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setToothpaste(String toothpaste) {
        this.toothpaste = toothpaste == null ? null : toothpaste.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.TOOTHPASTE_OTHER
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.TOOTHPASTE_OTHER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getToothpasteOther() {
        return toothpasteOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.TOOTHPASTE_OTHER
     *
     * @param toothpasteOther the value for tbl_patient_diagnostic_brushing_habits.TOOTHPASTE_OTHER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setToothpasteOther(String toothpasteOther) {
        this.toothpasteOther = toothpasteOther == null ? null : toothpasteOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_FREQUENCY
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.BRUSHING_FREQUENCY
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getBrushingFrequency() {
        return brushingFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_FREQUENCY
     *
     * @param brushingFrequency the value for tbl_patient_diagnostic_brushing_habits.BRUSHING_FREQUENCY
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setBrushingFrequency(String brushingFrequency) {
        this.brushingFrequency = brushingFrequency == null ? null : brushingFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.BRISTLES
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.BRISTLES
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getBristles() {
        return bristles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.BRISTLES
     *
     * @param bristles the value for tbl_patient_diagnostic_brushing_habits.BRISTLES
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setBristles(String bristles) {
        this.bristles = bristles == null ? null : bristles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_DURATION
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.BRUSHING_DURATION
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getBrushingDuration() {
        return brushingDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.BRUSHING_DURATION
     *
     * @param brushingDuration the value for tbl_patient_diagnostic_brushing_habits.BRUSHING_DURATION
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setBrushingDuration(String brushingDuration) {
        this.brushingDuration = brushingDuration == null ? null : brushingDuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_NONE
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_NONE
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getSupplementNone() {
        return supplementNone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_NONE
     *
     * @param supplementNone the value for tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_NONE
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setSupplementNone(String supplementNone) {
        this.supplementNone = supplementNone == null ? null : supplementNone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_FLOSS
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_FLOSS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getSupplementFloss() {
        return supplementFloss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_FLOSS
     *
     * @param supplementFloss the value for tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_FLOSS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setSupplementFloss(String supplementFloss) {
        this.supplementFloss = supplementFloss == null ? null : supplementFloss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_BOTTLE_BRUSHES
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_BOTTLE_BRUSHES
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getSupplementBottleBrushes() {
        return supplementBottleBrushes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_BOTTLE_BRUSHES
     *
     * @param supplementBottleBrushes the value for tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_BOTTLE_BRUSHES
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setSupplementBottleBrushes(String supplementBottleBrushes) {
        this.supplementBottleBrushes = supplementBottleBrushes == null ? null : supplementBottleBrushes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_SINGLE_TUFT
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_SINGLE_TUFT
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getSupplementSingleTuft() {
        return supplementSingleTuft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_SINGLE_TUFT
     *
     * @param supplementSingleTuft the value for tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_SINGLE_TUFT
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setSupplementSingleTuft(String supplementSingleTuft) {
        this.supplementSingleTuft = supplementSingleTuft == null ? null : supplementSingleTuft.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_WOODPICKS
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_WOODPICKS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getSupplementWoodpicks() {
        return supplementWoodpicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_WOODPICKS
     *
     * @param supplementWoodpicks the value for tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_WOODPICKS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setSupplementWoodpicks(String supplementWoodpicks) {
        this.supplementWoodpicks = supplementWoodpicks == null ? null : supplementWoodpicks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_IRRIGATORS
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_IRRIGATORS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getSupplementIrrigators() {
        return supplementIrrigators;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_IRRIGATORS
     *
     * @param supplementIrrigators the value for tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_IRRIGATORS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setSupplementIrrigators(String supplementIrrigators) {
        this.supplementIrrigators = supplementIrrigators == null ? null : supplementIrrigators.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_OTHER
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_OTHER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getSupplementOther() {
        return supplementOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_OTHER
     *
     * @param supplementOther the value for tbl_patient_diagnostic_brushing_habits.SUPPLEMENT_OTHER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setSupplementOther(String supplementOther) {
        this.supplementOther = supplementOther == null ? null : supplementOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.COMMENT
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.COMMENT
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.COMMENT
     *
     * @param comment the value for tbl_patient_diagnostic_brushing_habits.COMMENT
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.STATUS
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.STATUS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.STATUS
     *
     * @param status the value for tbl_patient_diagnostic_brushing_habits.STATUS
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.SORT_ORDER
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.SORT_ORDER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.SORT_ORDER
     *
     * @param sortOrder the value for tbl_patient_diagnostic_brushing_habits.SORT_ORDER
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.INSERT_USER_ID
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.INSERT_USER_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_patient_diagnostic_brushing_habits.INSERT_USER_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.INSERT_DATETIME
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.INSERT_DATETIME
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_patient_diagnostic_brushing_habits.INSERT_DATETIME
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.UPDATE_USER_ID
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.UPDATE_USER_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_patient_diagnostic_brushing_habits.UPDATE_USER_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_diagnostic_brushing_habits.UPDATE_DATETIME
     *
     * @return the value of tbl_patient_diagnostic_brushing_habits.UPDATE_DATETIME
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_brushing_habits.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_patient_diagnostic_brushing_habits.UPDATE_DATETIME
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}