package com.doerit.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatientDiagnosticMedicalRecord4Example {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public PatientDiagnosticMedicalRecord4Example() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNull() {
			addCriterion("PATIENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNotNull() {
			addCriterion("PATIENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPatientIdEqualTo(String value) {
			addCriterion("PATIENT_ID =", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotEqualTo(String value) {
			addCriterion("PATIENT_ID <>", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThan(String value) {
			addCriterion("PATIENT_ID >", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID >=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThan(String value) {
			addCriterion("PATIENT_ID <", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID <=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLike(String value) {
			addCriterion("PATIENT_ID like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotLike(String value) {
			addCriterion("PATIENT_ID not like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdIn(List<String> values) {
			addCriterion("PATIENT_ID in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotIn(List<String> values) {
			addCriterion("PATIENT_ID not in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdBetween(String value1, String value2) {
			addCriterion("PATIENT_ID between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotBetween(String value1, String value2) {
			addCriterion("PATIENT_ID not between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersIsNull() {
			addCriterion("BEHAVIOURAL_DISORDERS is null");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersIsNotNull() {
			addCriterion("BEHAVIOURAL_DISORDERS is not null");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersEqualTo(String value) {
			addCriterion("BEHAVIOURAL_DISORDERS =", value, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersNotEqualTo(String value) {
			addCriterion("BEHAVIOURAL_DISORDERS <>", value, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersGreaterThan(String value) {
			addCriterion("BEHAVIOURAL_DISORDERS >", value, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersGreaterThanOrEqualTo(String value) {
			addCriterion("BEHAVIOURAL_DISORDERS >=", value, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersLessThan(String value) {
			addCriterion("BEHAVIOURAL_DISORDERS <", value, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersLessThanOrEqualTo(String value) {
			addCriterion("BEHAVIOURAL_DISORDERS <=", value, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersLike(String value) {
			addCriterion("BEHAVIOURAL_DISORDERS like", value, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersNotLike(String value) {
			addCriterion("BEHAVIOURAL_DISORDERS not like", value, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersIn(List<String> values) {
			addCriterion("BEHAVIOURAL_DISORDERS in", values, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersNotIn(List<String> values) {
			addCriterion("BEHAVIOURAL_DISORDERS not in", values, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersBetween(String value1, String value2) {
			addCriterion("BEHAVIOURAL_DISORDERS between", value1, value2, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andBehaviouralDisordersNotBetween(String value1, String value2) {
			addCriterion("BEHAVIOURAL_DISORDERS not between", value1, value2, "behaviouralDisorders");
			return (Criteria) this;
		}

		public Criteria andTmdIsNull() {
			addCriterion("TMD is null");
			return (Criteria) this;
		}

		public Criteria andTmdIsNotNull() {
			addCriterion("TMD is not null");
			return (Criteria) this;
		}

		public Criteria andTmdEqualTo(String value) {
			addCriterion("TMD =", value, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdNotEqualTo(String value) {
			addCriterion("TMD <>", value, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdGreaterThan(String value) {
			addCriterion("TMD >", value, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdGreaterThanOrEqualTo(String value) {
			addCriterion("TMD >=", value, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdLessThan(String value) {
			addCriterion("TMD <", value, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdLessThanOrEqualTo(String value) {
			addCriterion("TMD <=", value, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdLike(String value) {
			addCriterion("TMD like", value, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdNotLike(String value) {
			addCriterion("TMD not like", value, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdIn(List<String> values) {
			addCriterion("TMD in", values, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdNotIn(List<String> values) {
			addCriterion("TMD not in", values, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdBetween(String value1, String value2) {
			addCriterion("TMD between", value1, value2, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdNotBetween(String value1, String value2) {
			addCriterion("TMD not between", value1, value2, "tmd");
			return (Criteria) this;
		}

		public Criteria andTmdOtherIsNull() {
			addCriterion("TMD_OTHER is null");
			return (Criteria) this;
		}

		public Criteria andTmdOtherIsNotNull() {
			addCriterion("TMD_OTHER is not null");
			return (Criteria) this;
		}

		public Criteria andTmdOtherEqualTo(String value) {
			addCriterion("TMD_OTHER =", value, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherNotEqualTo(String value) {
			addCriterion("TMD_OTHER <>", value, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherGreaterThan(String value) {
			addCriterion("TMD_OTHER >", value, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherGreaterThanOrEqualTo(String value) {
			addCriterion("TMD_OTHER >=", value, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherLessThan(String value) {
			addCriterion("TMD_OTHER <", value, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherLessThanOrEqualTo(String value) {
			addCriterion("TMD_OTHER <=", value, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherLike(String value) {
			addCriterion("TMD_OTHER like", value, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherNotLike(String value) {
			addCriterion("TMD_OTHER not like", value, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherIn(List<String> values) {
			addCriterion("TMD_OTHER in", values, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherNotIn(List<String> values) {
			addCriterion("TMD_OTHER not in", values, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherBetween(String value1, String value2) {
			addCriterion("TMD_OTHER between", value1, value2, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andTmdOtherNotBetween(String value1, String value2) {
			addCriterion("TMD_OTHER not between", value1, value2, "tmdOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsIsNull() {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS is null");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsIsNotNull() {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS is not null");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS =", value, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsNotEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS <>", value, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsGreaterThan(String value) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS >", value, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsGreaterThanOrEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS >=", value, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsLessThan(String value) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS <", value, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsLessThanOrEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS <=", value, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsLike(String value) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS like", value, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsNotLike(String value) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS not like", value, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsIn(List<String> values) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS in", values, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsNotIn(List<String> values) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS not in", values, "renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsBetween(String value1, String value2) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS between", value1, value2,
					"renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersChronicinfectionsNotBetween(String value1, String value2) {
			addCriterion("RENAL_DISORDERS_CHRONICINFECTIONS not between", value1, value2,
					"renalDisordersChronicinfections");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureIsNull() {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE is null");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureIsNotNull() {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE is not null");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE =", value, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureNotEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE <>", value, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureGreaterThan(String value) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE >", value, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureGreaterThanOrEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE >=", value, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureLessThan(String value) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE <", value, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureLessThanOrEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE <=", value, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureLike(String value) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE like", value, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureNotLike(String value) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE not like", value, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureIn(List<String> values) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE in", values, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureNotIn(List<String> values) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE not in", values, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureBetween(String value1, String value2) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE between", value1, value2, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersKidneyfailureNotBetween(String value1, String value2) {
			addCriterion("RENAL_DISORDERS_KIDNEYFAILURE not between", value1, value2, "renalDisordersKidneyfailure");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantIsNull() {
			addCriterion("RENAL_DISORDERS_TRANSPLANT is null");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantIsNotNull() {
			addCriterion("RENAL_DISORDERS_TRANSPLANT is not null");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT =", value, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantNotEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT <>", value, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantGreaterThan(String value) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT >", value, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantGreaterThanOrEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT >=", value, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantLessThan(String value) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT <", value, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantLessThanOrEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT <=", value, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantLike(String value) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT like", value, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantNotLike(String value) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT not like", value, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantIn(List<String> values) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT in", values, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantNotIn(List<String> values) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT not in", values, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantBetween(String value1, String value2) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT between", value1, value2, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersTransplantNotBetween(String value1, String value2) {
			addCriterion("RENAL_DISORDERS_TRANSPLANT not between", value1, value2, "renalDisordersTransplant");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherIsNull() {
			addCriterion("RENAL_DISORDERS_OTHER is null");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherIsNotNull() {
			addCriterion("RENAL_DISORDERS_OTHER is not null");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_OTHER =", value, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherNotEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_OTHER <>", value, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherGreaterThan(String value) {
			addCriterion("RENAL_DISORDERS_OTHER >", value, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherGreaterThanOrEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_OTHER >=", value, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherLessThan(String value) {
			addCriterion("RENAL_DISORDERS_OTHER <", value, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherLessThanOrEqualTo(String value) {
			addCriterion("RENAL_DISORDERS_OTHER <=", value, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherLike(String value) {
			addCriterion("RENAL_DISORDERS_OTHER like", value, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherNotLike(String value) {
			addCriterion("RENAL_DISORDERS_OTHER not like", value, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherIn(List<String> values) {
			addCriterion("RENAL_DISORDERS_OTHER in", values, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherNotIn(List<String> values) {
			addCriterion("RENAL_DISORDERS_OTHER not in", values, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherBetween(String value1, String value2) {
			addCriterion("RENAL_DISORDERS_OTHER between", value1, value2, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andRenalDisordersOtherNotBetween(String value1, String value2) {
			addCriterion("RENAL_DISORDERS_OTHER not between", value1, value2, "renalDisordersOther");
			return (Criteria) this;
		}

		public Criteria andPregnancyIsNull() {
			addCriterion("PREGNANCY is null");
			return (Criteria) this;
		}

		public Criteria andPregnancyIsNotNull() {
			addCriterion("PREGNANCY is not null");
			return (Criteria) this;
		}

		public Criteria andPregnancyEqualTo(String value) {
			addCriterion("PREGNANCY =", value, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyNotEqualTo(String value) {
			addCriterion("PREGNANCY <>", value, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyGreaterThan(String value) {
			addCriterion("PREGNANCY >", value, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyGreaterThanOrEqualTo(String value) {
			addCriterion("PREGNANCY >=", value, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyLessThan(String value) {
			addCriterion("PREGNANCY <", value, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyLessThanOrEqualTo(String value) {
			addCriterion("PREGNANCY <=", value, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyLike(String value) {
			addCriterion("PREGNANCY like", value, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyNotLike(String value) {
			addCriterion("PREGNANCY not like", value, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyIn(List<String> values) {
			addCriterion("PREGNANCY in", values, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyNotIn(List<String> values) {
			addCriterion("PREGNANCY not in", values, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyBetween(String value1, String value2) {
			addCriterion("PREGNANCY between", value1, value2, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andPregnancyNotBetween(String value1, String value2) {
			addCriterion("PREGNANCY not between", value1, value2, "pregnancy");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesIsNull() {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES is null");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesIsNotNull() {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES is not null");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesEqualTo(String value) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES =", value, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesNotEqualTo(String value) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES <>", value, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesGreaterThan(String value) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES >", value, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesGreaterThanOrEqualTo(String value) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES >=", value, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesLessThan(String value) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES <", value, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesLessThanOrEqualTo(String value) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES <=", value, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesLike(String value) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES like", value, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesNotLike(String value) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES not like", value, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesIn(List<String> values) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES in", values, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesNotIn(List<String> values) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES not in", values, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesBetween(String value1, String value2) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES between", value1, value2, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOnHormonalContraceptivesNotBetween(String value1, String value2) {
			addCriterion("ON_HORMONAL_CONTRACEPTIVES not between", value1, value2, "onHormonalContraceptives");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsIsNull() {
			addCriterion("OTHER_COMMENTS is null");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsIsNotNull() {
			addCriterion("OTHER_COMMENTS is not null");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsEqualTo(String value) {
			addCriterion("OTHER_COMMENTS =", value, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsNotEqualTo(String value) {
			addCriterion("OTHER_COMMENTS <>", value, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsGreaterThan(String value) {
			addCriterion("OTHER_COMMENTS >", value, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsGreaterThanOrEqualTo(String value) {
			addCriterion("OTHER_COMMENTS >=", value, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsLessThan(String value) {
			addCriterion("OTHER_COMMENTS <", value, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsLessThanOrEqualTo(String value) {
			addCriterion("OTHER_COMMENTS <=", value, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsLike(String value) {
			addCriterion("OTHER_COMMENTS like", value, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsNotLike(String value) {
			addCriterion("OTHER_COMMENTS not like", value, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsIn(List<String> values) {
			addCriterion("OTHER_COMMENTS in", values, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsNotIn(List<String> values) {
			addCriterion("OTHER_COMMENTS not in", values, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsBetween(String value1, String value2) {
			addCriterion("OTHER_COMMENTS between", value1, value2, "otherComments");
			return (Criteria) this;
		}

		public Criteria andOtherCommentsNotBetween(String value1, String value2) {
			addCriterion("OTHER_COMMENTS not between", value1, value2, "otherComments");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("COMMENT is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("COMMENT is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("COMMENT =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("COMMENT <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("COMMENT >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("COMMENT >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("COMMENT <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("COMMENT <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("COMMENT like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("COMMENT not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("COMMENT in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("COMMENT not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("COMMENT between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("COMMENT not between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNull() {
			addCriterion("SORT_ORDER is null");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNotNull() {
			addCriterion("SORT_ORDER is not null");
			return (Criteria) this;
		}

		public Criteria andSortOrderEqualTo(Integer value) {
			addCriterion("SORT_ORDER =", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotEqualTo(Integer value) {
			addCriterion("SORT_ORDER <>", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThan(Integer value) {
			addCriterion("SORT_ORDER >", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER >=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThan(Integer value) {
			addCriterion("SORT_ORDER <", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER <=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderIn(List<Integer> values) {
			addCriterion("SORT_ORDER in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotIn(List<Integer> values) {
			addCriterion("SORT_ORDER not in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER not between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNull() {
			addCriterion("INSERT_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNotNull() {
			addCriterion("INSERT_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdEqualTo(String value) {
			addCriterion("INSERT_USER_ID =", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotEqualTo(String value) {
			addCriterion("INSERT_USER_ID <>", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThan(String value) {
			addCriterion("INSERT_USER_ID >", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID >=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThan(String value) {
			addCriterion("INSERT_USER_ID <", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID <=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLike(String value) {
			addCriterion("INSERT_USER_ID like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotLike(String value) {
			addCriterion("INSERT_USER_ID not like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIn(List<String> values) {
			addCriterion("INSERT_USER_ID in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotIn(List<String> values) {
			addCriterion("INSERT_USER_ID not in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID not between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("INSERT_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("INSERT_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("INSERT_DATETIME =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("INSERT_DATETIME >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("INSERT_DATETIME <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("INSERT_DATETIME in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("INSERT_DATETIME not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNull() {
			addCriterion("UPDATE_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNotNull() {
			addCriterion("UPDATE_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdEqualTo(String value) {
			addCriterion("UPDATE_USER_ID =", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThan(String value) {
			addCriterion("UPDATE_USER_ID >", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThan(String value) {
			addCriterion("UPDATE_USER_ID <", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLike(String value) {
			addCriterion("UPDATE_USER_ID like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotLike(String value) {
			addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIn(List<String> values) {
			addCriterion("UPDATE_USER_ID in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotIn(List<String> values) {
			addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("UPDATE_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("UPDATE_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("UPDATE_DATETIME >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("UPDATE_DATETIME <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_diagnostic_medicalrecord4
	 * @mbg.generated  Sun May 06 18:12:59 IST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_diagnostic_medicalrecord4
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 22 17:47:16 IST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}