package com.doerit.model;

import java.util.Date;

public class PatientDiagnosticDietaryHabits implements InsertUpdate {
	
	//private final static String CARBONIC = "Carbonic";
    @Override
	public String toString() {
		return "PatientDiagnosticDietaryHabits [id=" + id + ", patientId=" + patientId + ", sugarConsumption="
				+ sugarConsumption + ", beverageCarbonic=" + beverageCarbonic + ", beverageFruit=" + beverageFruit
				+ ", other=" + other + ", employment=" + employment + ", comment=" + comment + ", status=" + status
				+ ", sortOrder=" + sortOrder + ", insertUserId=" + insertUserId + ", insertDatetime=" + insertDatetime
				+ ", updateUserId=" + updateUserId + ", updateDatetime=" + updateDatetime + "]";
	}

   
	private String id;
    private String patientId;
    private String sugarConsumption;
    private String beverageCarbonic;
    private String beverageFruit;
    private String other;
    private String employment;
    private String comment;
    private Byte status;
    private Integer sortOrder;
    private String insertUserId;
    private Date insertDatetime;
    private String updateUserId;
    private Date updateDatetime;
    
    private boolean beverageCarbonicCheck;
    private boolean beverageFruitCheck;
    

    public String getId() {
        return id;
    }
    
    public String getBeverageCarbonic() {
		return beverageCarbonic;
	}

	public void setBeverageCarbonic(String beverageCarbonic) {
		//this.beverageCarbonic = beverageCarbonic;
		this.beverageCarbonic = beverageCarbonic == null ? null : beverageCarbonic.trim();
	}

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_diagnostic_dietary_habits.PATIENT_ID
     *
     * @param patientId the value for tbl_patient_diagnostic_dietary_habits.PATIENT_ID
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

   
    public String getSugarConsumption() {
        return sugarConsumption;
    }

    
    public void setSugarConsumption(String sugarConsumption) {
        this.sugarConsumption = sugarConsumption == null ? null : sugarConsumption.trim();
    }

   /* public String getBeverageCarbonic() {
    	if(this.beverageCarbonic != null && this.beverageCarbonic.equals(CARBONIC)) {
    		this.beverageCarbonicCheck = true;
    	} else {
    		this.beverageCarbonicCheck = false;
    	}
        return beverageCarbonic;
    }*/

   /* public void setBeverageCarbonic(String beverageCarbonic) {
    	if(this.beverageCarbonicCheck) {
    		this.beverageCarbonic = CARBONIC;
    	} else {
    		this.beverageCarbonic = null;
    	}
    	
        this.beverageCarbonic = beverageCarbonic == null ? null : beverageCarbonic.trim();
    }*/

    public String getBeverageFruit() {
        return beverageFruit;
    }


    public void setBeverageFruit(String beverageFruit) {
        this.beverageFruit = beverageFruit == null ? null : beverageFruit.trim();
    }

   
    public String getOther() {
        return other;
    }

    
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

   
    public String getEmployment() {
        return employment;
    }

  
    public void setEmployment(String employment) {
        this.employment = employment == null ? null : employment.trim();
    }

  
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

  
    public Byte getStatus() {
        return status;
    }

 
    public void setStatus(Byte status) {
        this.status = status;
    }

    
    public Integer getSortOrder() {
        return sortOrder;
    }

  
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public String getInsertUserId() {
        return insertUserId;
    }

   
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    
    public Date getInsertDatetime() {
        return insertDatetime;
    }

  
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

   
    public String getUpdateUserId() {
        return updateUserId;
    }

    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

   
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

	public boolean isBeverageCarbonicCheck() {
		return beverageCarbonicCheck;
	}

	public void setBeverageCarbonicCheck(boolean beverageCarbonicCheck) {
		this.beverageCarbonicCheck = beverageCarbonicCheck;
	}

	public boolean isBeverageFruitCheck() {
		return beverageFruitCheck;
	}

	public void setBeverageFruitCheck(boolean beverageFruitCheck) {
		this.beverageFruitCheck = beverageFruitCheck;
	}
    
    
}