package com.doerit.model;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class PatientRequestConebeam {

	public static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	
	private String dateRequestedString;
	private String dateAppointmentString;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.PATIENT_ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String patientId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.URGENT
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String urgent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.PREVIOUS_XRAY_INFO
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String previousXrayInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.CLINICAL_NOTE
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String clinicalNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.CONSULTANT_NAME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String consultantName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.HOSPITAL_NAME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String hospitalName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.CONSULTANT_SIGN
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String consultantSign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.DATE_REQUESTED
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private Date dateRequested;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.DATE_APPOINTMENT
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private Date dateAppointment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.CD_GIVEN
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String cdGiven;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.PROPERTY_VALUE
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String propertyValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.COMMENT
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.STATUS
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.SORT_ORDER
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.INSERT_USER_ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String insertUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.UPDATE_USER_ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private String updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.INSERT_DATETIME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_patient_request_conebeam.UPDATE_DATETIME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.ID
	 * @return  the value of tbl_patient_request_conebeam.ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.ID
	 * @param id  the value for tbl_patient_request_conebeam.ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.PATIENT_ID
	 * @return  the value of tbl_patient_request_conebeam.PATIENT_ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getPatientId() {
		return patientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.PATIENT_ID
	 * @param patientId  the value for tbl_patient_request_conebeam.PATIENT_ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setPatientId(String patientId) {
		this.patientId = patientId == null ? null : patientId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.URGENT
	 * @return  the value of tbl_patient_request_conebeam.URGENT
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getUrgent() {
		return urgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.URGENT
	 * @param urgent  the value for tbl_patient_request_conebeam.URGENT
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setUrgent(String urgent) {
		this.urgent = urgent == null ? null : urgent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.PREVIOUS_XRAY_INFO
	 * @return  the value of tbl_patient_request_conebeam.PREVIOUS_XRAY_INFO
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getPreviousXrayInfo() {
		return previousXrayInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.PREVIOUS_XRAY_INFO
	 * @param previousXrayInfo  the value for tbl_patient_request_conebeam.PREVIOUS_XRAY_INFO
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setPreviousXrayInfo(String previousXrayInfo) {
		this.previousXrayInfo = previousXrayInfo == null ? null : previousXrayInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.CLINICAL_NOTE
	 * @return  the value of tbl_patient_request_conebeam.CLINICAL_NOTE
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getClinicalNote() {
		return clinicalNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.CLINICAL_NOTE
	 * @param clinicalNote  the value for tbl_patient_request_conebeam.CLINICAL_NOTE
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setClinicalNote(String clinicalNote) {
		this.clinicalNote = clinicalNote == null ? null : clinicalNote.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.CONSULTANT_NAME
	 * @return  the value of tbl_patient_request_conebeam.CONSULTANT_NAME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getConsultantName() {
		return consultantName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.CONSULTANT_NAME
	 * @param consultantName  the value for tbl_patient_request_conebeam.CONSULTANT_NAME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setConsultantName(String consultantName) {
		this.consultantName = consultantName == null ? null : consultantName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.HOSPITAL_NAME
	 * @return  the value of tbl_patient_request_conebeam.HOSPITAL_NAME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getHospitalName() {
		return hospitalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.HOSPITAL_NAME
	 * @param hospitalName  the value for tbl_patient_request_conebeam.HOSPITAL_NAME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName == null ? null : hospitalName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.CONSULTANT_SIGN
	 * @return  the value of tbl_patient_request_conebeam.CONSULTANT_SIGN
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getConsultantSign() {
		return consultantSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.CONSULTANT_SIGN
	 * @param consultantSign  the value for tbl_patient_request_conebeam.CONSULTANT_SIGN
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setConsultantSign(String consultantSign) {
		this.consultantSign = consultantSign == null ? null : consultantSign.trim();
	}


	public Date getDateRequested() {
		return dateRequested;
	}


	public void setDateRequested(Date dateRequested) {
		this.dateRequested = dateRequested;
	}

	public String getDateRequestedString() {
		if(this.dateRequested != null) {
			dateRequestedString = sdf.format(this.dateRequested);
		}
		return dateRequestedString;
	}

	public void setDateRequestedString(String dateRequestedString) {
		this.dateRequestedString = dateRequestedString;
		
		if(this.dateRequestedString != null && !this.dateRequestedString.isEmpty()) {
			
			try {
				Date date = sdf.parse(this.dateRequestedString);
				this.dateRequested = date;
			} catch (ParseException e) {
				e.printStackTrace();
			}
		} else {
			this.dateRequested = null;
		}
	}	

	public String getDateAppointmentString() {
		if(this.dateAppointment != null) {
			dateAppointmentString = sdf.format(this.dateAppointment);
		}
		return dateAppointmentString;
	}

	public void setDateAppointmentString(String dateAppointmentString) {
		this.dateAppointmentString = dateAppointmentString;
		
		if(this.dateAppointmentString != null && !this.dateAppointmentString.isEmpty()) {
			
			try {
				Date date = sdf.parse(this.dateAppointmentString);
				this.dateAppointment = date;
			} catch (ParseException e) {
				e.printStackTrace();
			}
		} else {
			this.dateAppointment = null;
		}
	}	
	

	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.DATE_APPOINTMENT
	 * @return  the value of tbl_patient_request_conebeam.DATE_APPOINTMENT
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public Date getDateAppointment() {
		return dateAppointment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.DATE_APPOINTMENT
	 * @param dateAppointment  the value for tbl_patient_request_conebeam.DATE_APPOINTMENT
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setDateAppointment(Date dateAppointment) {
		this.dateAppointment = dateAppointment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.CD_GIVEN
	 * @return  the value of tbl_patient_request_conebeam.CD_GIVEN
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getCdGiven() {
		return cdGiven;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.CD_GIVEN
	 * @param cdGiven  the value for tbl_patient_request_conebeam.CD_GIVEN
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setCdGiven(String cdGiven) {
		this.cdGiven = cdGiven == null ? null : cdGiven.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.PROPERTY_VALUE
	 * @return  the value of tbl_patient_request_conebeam.PROPERTY_VALUE
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getPropertyValue() {
		return propertyValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.PROPERTY_VALUE
	 * @param propertyValue  the value for tbl_patient_request_conebeam.PROPERTY_VALUE
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue == null ? null : propertyValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.COMMENT
	 * @return  the value of tbl_patient_request_conebeam.COMMENT
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.COMMENT
	 * @param comment  the value for tbl_patient_request_conebeam.COMMENT
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setComment(String comment) {
		this.comment = comment == null ? null : comment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.STATUS
	 * @return  the value of tbl_patient_request_conebeam.STATUS
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.STATUS
	 * @param status  the value for tbl_patient_request_conebeam.STATUS
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.SORT_ORDER
	 * @return  the value of tbl_patient_request_conebeam.SORT_ORDER
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.SORT_ORDER
	 * @param sortOrder  the value for tbl_patient_request_conebeam.SORT_ORDER
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.INSERT_USER_ID
	 * @return  the value of tbl_patient_request_conebeam.INSERT_USER_ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getInsertUserId() {
		return insertUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.INSERT_USER_ID
	 * @param insertUserId  the value for tbl_patient_request_conebeam.INSERT_USER_ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setInsertUserId(String insertUserId) {
		this.insertUserId = insertUserId == null ? null : insertUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.UPDATE_USER_ID
	 * @return  the value of tbl_patient_request_conebeam.UPDATE_USER_ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.UPDATE_USER_ID
	 * @param updateUserId  the value for tbl_patient_request_conebeam.UPDATE_USER_ID
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId == null ? null : updateUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.INSERT_DATETIME
	 * @return  the value of tbl_patient_request_conebeam.INSERT_DATETIME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.INSERT_DATETIME
	 * @param insertDatetime  the value for tbl_patient_request_conebeam.INSERT_DATETIME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_patient_request_conebeam.UPDATE_DATETIME
	 * @return  the value of tbl_patient_request_conebeam.UPDATE_DATETIME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_patient_request_conebeam.UPDATE_DATETIME
	 * @param updateDatetime  the value for tbl_patient_request_conebeam.UPDATE_DATETIME
	 * @mbg.generated  Tue Feb 13 22:08:53 IST 2018
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}
}