package com.doerit.model;

import java.util.Date;

public class PatientRequestHBI {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.PATIENT_ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private String patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.CLINICAL_HISTORY
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private String clinicalHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.TYPE_OF_TEST
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private String typeOfTest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.TYPE_OF_TEST_OTHER
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private String typeOfTestOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.COMMENT
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.STATUS
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.SORT_ORDER
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.INSERT_USER_ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private String insertUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.UPDATE_USER_ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.INSERT_DATETIME
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private Date insertDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_patient_request_hbi.UPDATE_DATETIME
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.ID
     *
     * @return the value of tbl_patient_request_hbi.ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.ID
     *
     * @param id the value for tbl_patient_request_hbi.ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.PATIENT_ID
     *
     * @return the value of tbl_patient_request_hbi.PATIENT_ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.PATIENT_ID
     *
     * @param patientId the value for tbl_patient_request_hbi.PATIENT_ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.CLINICAL_HISTORY
     *
     * @return the value of tbl_patient_request_hbi.CLINICAL_HISTORY
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public String getClinicalHistory() {
        return clinicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.CLINICAL_HISTORY
     *
     * @param clinicalHistory the value for tbl_patient_request_hbi.CLINICAL_HISTORY
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setClinicalHistory(String clinicalHistory) {
        this.clinicalHistory = clinicalHistory == null ? null : clinicalHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.TYPE_OF_TEST
     *
     * @return the value of tbl_patient_request_hbi.TYPE_OF_TEST
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public String getTypeOfTest() {
        return typeOfTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.TYPE_OF_TEST
     *
     * @param typeOfTest the value for tbl_patient_request_hbi.TYPE_OF_TEST
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setTypeOfTest(String typeOfTest) {
        this.typeOfTest = typeOfTest == null ? null : typeOfTest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.TYPE_OF_TEST_OTHER
     *
     * @return the value of tbl_patient_request_hbi.TYPE_OF_TEST_OTHER
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public String getTypeOfTestOther() {
        return typeOfTestOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.TYPE_OF_TEST_OTHER
     *
     * @param typeOfTestOther the value for tbl_patient_request_hbi.TYPE_OF_TEST_OTHER
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setTypeOfTestOther(String typeOfTestOther) {
        this.typeOfTestOther = typeOfTestOther == null ? null : typeOfTestOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.COMMENT
     *
     * @return the value of tbl_patient_request_hbi.COMMENT
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.COMMENT
     *
     * @param comment the value for tbl_patient_request_hbi.COMMENT
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.STATUS
     *
     * @return the value of tbl_patient_request_hbi.STATUS
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.STATUS
     *
     * @param status the value for tbl_patient_request_hbi.STATUS
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.SORT_ORDER
     *
     * @return the value of tbl_patient_request_hbi.SORT_ORDER
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.SORT_ORDER
     *
     * @param sortOrder the value for tbl_patient_request_hbi.SORT_ORDER
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.INSERT_USER_ID
     *
     * @return the value of tbl_patient_request_hbi.INSERT_USER_ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_patient_request_hbi.INSERT_USER_ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.UPDATE_USER_ID
     *
     * @return the value of tbl_patient_request_hbi.UPDATE_USER_ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_patient_request_hbi.UPDATE_USER_ID
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.INSERT_DATETIME
     *
     * @return the value of tbl_patient_request_hbi.INSERT_DATETIME
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_patient_request_hbi.INSERT_DATETIME
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_request_hbi.UPDATE_DATETIME
     *
     * @return the value of tbl_patient_request_hbi.UPDATE_DATETIME
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_request_hbi.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_patient_request_hbi.UPDATE_DATETIME
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}