package com.doerit.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatientDiagnosticDentalHistoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public PatientDiagnosticDentalHistoryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNull() {
			addCriterion("PATIENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andPatientIdIsNotNull() {
			addCriterion("PATIENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPatientIdEqualTo(String value) {
			addCriterion("PATIENT_ID =", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotEqualTo(String value) {
			addCriterion("PATIENT_ID <>", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThan(String value) {
			addCriterion("PATIENT_ID >", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID >=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThan(String value) {
			addCriterion("PATIENT_ID <", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLessThanOrEqualTo(String value) {
			addCriterion("PATIENT_ID <=", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdLike(String value) {
			addCriterion("PATIENT_ID like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotLike(String value) {
			addCriterion("PATIENT_ID not like", value, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdIn(List<String> values) {
			addCriterion("PATIENT_ID in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotIn(List<String> values) {
			addCriterion("PATIENT_ID not in", values, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdBetween(String value1, String value2) {
			addCriterion("PATIENT_ID between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andPatientIdNotBetween(String value1, String value2) {
			addCriterion("PATIENT_ID not between", value1, value2, "patientId");
			return (Criteria) this;
		}

		public Criteria andExtractionIsNull() {
			addCriterion("EXTRACTION is null");
			return (Criteria) this;
		}

		public Criteria andExtractionIsNotNull() {
			addCriterion("EXTRACTION is not null");
			return (Criteria) this;
		}

		public Criteria andExtractionEqualTo(String value) {
			addCriterion("EXTRACTION =", value, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionNotEqualTo(String value) {
			addCriterion("EXTRACTION <>", value, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionGreaterThan(String value) {
			addCriterion("EXTRACTION >", value, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionGreaterThanOrEqualTo(String value) {
			addCriterion("EXTRACTION >=", value, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionLessThan(String value) {
			addCriterion("EXTRACTION <", value, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionLessThanOrEqualTo(String value) {
			addCriterion("EXTRACTION <=", value, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionLike(String value) {
			addCriterion("EXTRACTION like", value, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionNotLike(String value) {
			addCriterion("EXTRACTION not like", value, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionIn(List<String> values) {
			addCriterion("EXTRACTION in", values, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionNotIn(List<String> values) {
			addCriterion("EXTRACTION not in", values, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionBetween(String value1, String value2) {
			addCriterion("EXTRACTION between", value1, value2, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionNotBetween(String value1, String value2) {
			addCriterion("EXTRACTION not between", value1, value2, "extraction");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsIsNull() {
			addCriterion("EXTRACTION_COMPLICATIONS is null");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsIsNotNull() {
			addCriterion("EXTRACTION_COMPLICATIONS is not null");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsEqualTo(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS =", value, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsNotEqualTo(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS <>", value, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsGreaterThan(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS >", value, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsGreaterThanOrEqualTo(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS >=", value, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsLessThan(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS <", value, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsLessThanOrEqualTo(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS <=", value, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsLike(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS like", value, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsNotLike(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS not like", value, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsIn(List<String> values) {
			addCriterion("EXTRACTION_COMPLICATIONS in", values, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsNotIn(List<String> values) {
			addCriterion("EXTRACTION_COMPLICATIONS not in", values, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsBetween(String value1, String value2) {
			addCriterion("EXTRACTION_COMPLICATIONS between", value1, value2, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsNotBetween(String value1, String value2) {
			addCriterion("EXTRACTION_COMPLICATIONS not between", value1, value2, "extractionComplications");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeIsNull() {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeIsNotNull() {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeEqualTo(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE =", value, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeNotEqualTo(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE <>", value, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeGreaterThan(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE >", value, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeGreaterThanOrEqualTo(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE >=", value, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeLessThan(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE <", value, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeLessThanOrEqualTo(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE <=", value, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeLike(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE like", value, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeNotLike(String value) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE not like", value, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeIn(List<String> values) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE in", values, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeNotIn(List<String> values) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE not in", values, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeBetween(String value1, String value2) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE between", value1, value2, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andExtractionComplicationsTypeNotBetween(String value1, String value2) {
			addCriterion("EXTRACTION_COMPLICATIONS_TYPE not between", value1, value2, "extractionComplicationsType");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryIsNull() {
			addCriterion("ORAL_SURGERY is null");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryIsNotNull() {
			addCriterion("ORAL_SURGERY is not null");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryEqualTo(String value) {
			addCriterion("ORAL_SURGERY =", value, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryNotEqualTo(String value) {
			addCriterion("ORAL_SURGERY <>", value, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryGreaterThan(String value) {
			addCriterion("ORAL_SURGERY >", value, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryGreaterThanOrEqualTo(String value) {
			addCriterion("ORAL_SURGERY >=", value, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryLessThan(String value) {
			addCriterion("ORAL_SURGERY <", value, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryLessThanOrEqualTo(String value) {
			addCriterion("ORAL_SURGERY <=", value, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryLike(String value) {
			addCriterion("ORAL_SURGERY like", value, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryNotLike(String value) {
			addCriterion("ORAL_SURGERY not like", value, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryIn(List<String> values) {
			addCriterion("ORAL_SURGERY in", values, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryNotIn(List<String> values) {
			addCriterion("ORAL_SURGERY not in", values, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryBetween(String value1, String value2) {
			addCriterion("ORAL_SURGERY between", value1, value2, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andOralSurgeryNotBetween(String value1, String value2) {
			addCriterion("ORAL_SURGERY not between", value1, value2, "oralSurgery");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxIsNull() {
			addCriterion("PERIODONTAL_RX is null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxIsNotNull() {
			addCriterion("PERIODONTAL_RX is not null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxEqualTo(String value) {
			addCriterion("PERIODONTAL_RX =", value, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxNotEqualTo(String value) {
			addCriterion("PERIODONTAL_RX <>", value, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxGreaterThan(String value) {
			addCriterion("PERIODONTAL_RX >", value, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxGreaterThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX >=", value, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxLessThan(String value) {
			addCriterion("PERIODONTAL_RX <", value, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxLessThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX <=", value, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxLike(String value) {
			addCriterion("PERIODONTAL_RX like", value, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxNotLike(String value) {
			addCriterion("PERIODONTAL_RX not like", value, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxIn(List<String> values) {
			addCriterion("PERIODONTAL_RX in", values, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxNotIn(List<String> values) {
			addCriterion("PERIODONTAL_RX not in", values, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX between", value1, value2, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxNotBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX not between", value1, value2, "periodontalRx");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingIsNull() {
			addCriterion("PERIODONTAL_RX_SCALING is null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingIsNotNull() {
			addCriterion("PERIODONTAL_RX_SCALING is not null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_SCALING =", value, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingNotEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_SCALING <>", value, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingGreaterThan(String value) {
			addCriterion("PERIODONTAL_RX_SCALING >", value, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingGreaterThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_SCALING >=", value, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingLessThan(String value) {
			addCriterion("PERIODONTAL_RX_SCALING <", value, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingLessThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_SCALING <=", value, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingLike(String value) {
			addCriterion("PERIODONTAL_RX_SCALING like", value, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingNotLike(String value) {
			addCriterion("PERIODONTAL_RX_SCALING not like", value, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingIn(List<String> values) {
			addCriterion("PERIODONTAL_RX_SCALING in", values, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingNotIn(List<String> values) {
			addCriterion("PERIODONTAL_RX_SCALING not in", values, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX_SCALING between", value1, value2, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxScalingNotBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX_SCALING not between", value1, value2, "periodontalRxScaling");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentIsNull() {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT is null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentIsNotNull() {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT is not null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT =", value, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentNotEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT <>", value, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentGreaterThan(String value) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT >", value, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentGreaterThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT >=", value, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentLessThan(String value) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT <", value, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentLessThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT <=", value, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentLike(String value) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT like", value, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentNotLike(String value) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT not like", value, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentIn(List<String> values) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT in", values, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentNotIn(List<String> values) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT not in", values, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT between", value1, value2, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxRootdebrimentNotBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX_ROOTDEBRIMENT not between", value1, value2, "periodontalRxRootdebriment");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalIsNull() {
			addCriterion("PERIODONTAL_RX_SURGICAL is null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalIsNotNull() {
			addCriterion("PERIODONTAL_RX_SURGICAL is not null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_SURGICAL =", value, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalNotEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_SURGICAL <>", value, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalGreaterThan(String value) {
			addCriterion("PERIODONTAL_RX_SURGICAL >", value, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalGreaterThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_SURGICAL >=", value, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalLessThan(String value) {
			addCriterion("PERIODONTAL_RX_SURGICAL <", value, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalLessThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_SURGICAL <=", value, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalLike(String value) {
			addCriterion("PERIODONTAL_RX_SURGICAL like", value, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalNotLike(String value) {
			addCriterion("PERIODONTAL_RX_SURGICAL not like", value, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalIn(List<String> values) {
			addCriterion("PERIODONTAL_RX_SURGICAL in", values, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalNotIn(List<String> values) {
			addCriterion("PERIODONTAL_RX_SURGICAL not in", values, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX_SURGICAL between", value1, value2, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxSurgicalNotBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX_SURGICAL not between", value1, value2, "periodontalRxSurgical");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceIsNull() {
			addCriterion("PERIODONTAL_RX_MAINTENANCE is null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceIsNotNull() {
			addCriterion("PERIODONTAL_RX_MAINTENANCE is not null");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE =", value, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceNotEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE <>", value, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceGreaterThan(String value) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE >", value, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceGreaterThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE >=", value, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceLessThan(String value) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE <", value, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceLessThanOrEqualTo(String value) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE <=", value, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceLike(String value) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE like", value, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceNotLike(String value) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE not like", value, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceIn(List<String> values) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE in", values, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceNotIn(List<String> values) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE not in", values, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE between", value1, value2, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andPeriodontalRxMaintenanceNotBetween(String value1, String value2) {
			addCriterion("PERIODONTAL_RX_MAINTENANCE not between", value1, value2, "periodontalRxMaintenance");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentIsNull() {
			addCriterion("ORTHODONTIC_TREATMENT is null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentIsNotNull() {
			addCriterion("ORTHODONTIC_TREATMENT is not null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT =", value, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentNotEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT <>", value, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentGreaterThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT >", value, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentGreaterThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT >=", value, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentLessThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT <", value, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentLessThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT <=", value, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT like", value, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentNotLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT not like", value, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT in", values, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentNotIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT not in", values, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT between", value1, value2, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentNotBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT not between", value1, value2, "orthodonticTreatment");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedIsNull() {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED is null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedIsNotNull() {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED is not null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED =", value, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedNotEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED <>", value, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedGreaterThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED >", value, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedGreaterThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED >=", value, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedLessThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED <", value, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedLessThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED <=", value, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED like", value, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedNotLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED not like", value, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED in", values, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedNotIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED not in", values, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED between", value1, value2, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFixedNotBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT_FIXED not between", value1, value2, "orthodonticTreatmentFixed");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableIsNull() {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE is null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableIsNotNull() {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE is not null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE =", value, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableNotEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE <>", value, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableGreaterThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE >", value, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableGreaterThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE >=", value, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableLessThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE <", value, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableLessThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE <=", value, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE like", value, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableNotLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE not like", value, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE in", values, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableNotIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE not in", values, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE between", value1, value2, "orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentRemovableNotBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT_REMOVABLE not between", value1, value2,
					"orthodonticTreatmentRemovable");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalIsNull() {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL is null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalIsNotNull() {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL is not null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL =", value, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalNotEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL <>", value, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalGreaterThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL >", value, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalGreaterThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL >=", value, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalLessThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL <", value, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalLessThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL <=", value, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL like", value, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalNotLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL not like", value, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL in", values, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalNotIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL not in", values, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL between", value1, value2, "orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentFunctionalNotBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT_FUNCTIONAL not between", value1, value2,
					"orthodonticTreatmentFunctional");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsIsNull() {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS is null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsIsNotNull() {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS is not null");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS =", value, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsNotEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS <>", value, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsGreaterThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS >", value, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsGreaterThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS >=", value, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsLessThan(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS <", value, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsLessThanOrEqualTo(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS <=", value, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS like", value, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsNotLike(String value) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS not like", value, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS in", values, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsNotIn(List<String> values) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS not in", values, "orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS between", value1, value2,
					"orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andOrthodonticTreatmentComplicationsNotBetween(String value1, String value2) {
			addCriterion("ORTHODONTIC_TREATMENT_COMPLICATIONS not between", value1, value2,
					"orthodonticTreatmentComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxIsNull() {
			addCriterion("RESTORATIVE_RX is null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxIsNotNull() {
			addCriterion("RESTORATIVE_RX is not null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEqualTo(String value) {
			addCriterion("RESTORATIVE_RX =", value, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxNotEqualTo(String value) {
			addCriterion("RESTORATIVE_RX <>", value, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxGreaterThan(String value) {
			addCriterion("RESTORATIVE_RX >", value, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxGreaterThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX >=", value, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxLessThan(String value) {
			addCriterion("RESTORATIVE_RX <", value, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxLessThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX <=", value, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxLike(String value) {
			addCriterion("RESTORATIVE_RX like", value, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxNotLike(String value) {
			addCriterion("RESTORATIVE_RX not like", value, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxIn(List<String> values) {
			addCriterion("RESTORATIVE_RX in", values, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxNotIn(List<String> values) {
			addCriterion("RESTORATIVE_RX not in", values, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX between", value1, value2, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxNotBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX not between", value1, value2, "restorativeRx");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsIsNull() {
			addCriterion("RESTORATIVE_RX_ENDODONTICS is null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsIsNotNull() {
			addCriterion("RESTORATIVE_RX_ENDODONTICS is not null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS =", value, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsNotEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS <>", value, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsGreaterThan(String value) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS >", value, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsGreaterThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS >=", value, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsLessThan(String value) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS <", value, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsLessThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS <=", value, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsLike(String value) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS like", value, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsNotLike(String value) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS not like", value, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS in", values, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsNotIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS not in", values, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS between", value1, value2, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxEndodonticsNotBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_ENDODONTICS not between", value1, value2, "restorativeRxEndodontics");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisIsNull() {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS is null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisIsNotNull() {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS is not null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS =", value, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisNotEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS <>", value, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisGreaterThan(String value) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS >", value, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisGreaterThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS >=", value, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisLessThan(String value) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS <", value, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisLessThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS <=", value, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisLike(String value) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS like", value, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisNotLike(String value) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS not like", value, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS in", values, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisNotIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS not in", values, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS between", value1, value2, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxFixedprosthesisNotBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_FIXEDPROSTHESIS not between", value1, value2, "restorativeRxFixedprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisIsNull() {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS is null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisIsNotNull() {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS is not null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS =", value, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisNotEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS <>", value, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisGreaterThan(String value) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS >", value, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisGreaterThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS >=", value, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisLessThan(String value) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS <", value, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisLessThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS <=", value, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisLike(String value) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS like", value, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisNotLike(String value) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS not like", value, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS in", values, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisNotIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS not in", values, "restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS between", value1, value2,
					"restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRemovableprosthesisNotBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_REMOVABLEPROSTHESIS not between", value1, value2,
					"restorativeRxRemovableprosthesis");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsIsNull() {
			addCriterion("RESTORATIVE_RX_RESTORATIONS is null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsIsNotNull() {
			addCriterion("RESTORATIVE_RX_RESTORATIONS is not null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS =", value, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsNotEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS <>", value, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsGreaterThan(String value) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS >", value, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsGreaterThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS >=", value, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsLessThan(String value) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS <", value, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsLessThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS <=", value, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsLike(String value) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS like", value, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsNotLike(String value) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS not like", value, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS in", values, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsNotIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS not in", values, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS between", value1, value2, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxRestorationsNotBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_RESTORATIONS not between", value1, value2, "restorativeRxRestorations");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsIsNull() {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS is null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsIsNotNull() {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS is not null");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS =", value, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsNotEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS <>", value, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsGreaterThan(String value) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS >", value, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsGreaterThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS >=", value, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsLessThan(String value) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS <", value, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsLessThanOrEqualTo(String value) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS <=", value, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsLike(String value) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS like", value, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsNotLike(String value) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS not like", value, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS in", values, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsNotIn(List<String> values) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS not in", values, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS between", value1, value2, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andRestorativeRxComplicationsNotBetween(String value1, String value2) {
			addCriterion("RESTORATIVE_RX_COMPLICATIONS not between", value1, value2, "restorativeRxComplications");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("COMMENT is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("COMMENT is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("COMMENT =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("COMMENT <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("COMMENT >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("COMMENT >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("COMMENT <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("COMMENT <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("COMMENT like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("COMMENT not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("COMMENT in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("COMMENT not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("COMMENT between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("COMMENT not between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNull() {
			addCriterion("SORT_ORDER is null");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNotNull() {
			addCriterion("SORT_ORDER is not null");
			return (Criteria) this;
		}

		public Criteria andSortOrderEqualTo(Integer value) {
			addCriterion("SORT_ORDER =", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotEqualTo(Integer value) {
			addCriterion("SORT_ORDER <>", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThan(Integer value) {
			addCriterion("SORT_ORDER >", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER >=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThan(Integer value) {
			addCriterion("SORT_ORDER <", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER <=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderIn(List<Integer> values) {
			addCriterion("SORT_ORDER in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotIn(List<Integer> values) {
			addCriterion("SORT_ORDER not in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER not between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNull() {
			addCriterion("INSERT_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNotNull() {
			addCriterion("INSERT_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdEqualTo(String value) {
			addCriterion("INSERT_USER_ID =", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotEqualTo(String value) {
			addCriterion("INSERT_USER_ID <>", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThan(String value) {
			addCriterion("INSERT_USER_ID >", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID >=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThan(String value) {
			addCriterion("INSERT_USER_ID <", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID <=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLike(String value) {
			addCriterion("INSERT_USER_ID like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotLike(String value) {
			addCriterion("INSERT_USER_ID not like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIn(List<String> values) {
			addCriterion("INSERT_USER_ID in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotIn(List<String> values) {
			addCriterion("INSERT_USER_ID not in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID not between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("INSERT_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("INSERT_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("INSERT_DATETIME =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("INSERT_DATETIME >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("INSERT_DATETIME <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("INSERT_DATETIME in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("INSERT_DATETIME not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNull() {
			addCriterion("UPDATE_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNotNull() {
			addCriterion("UPDATE_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdEqualTo(String value) {
			addCriterion("UPDATE_USER_ID =", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThan(String value) {
			addCriterion("UPDATE_USER_ID >", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThan(String value) {
			addCriterion("UPDATE_USER_ID <", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLike(String value) {
			addCriterion("UPDATE_USER_ID like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotLike(String value) {
			addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIn(List<String> values) {
			addCriterion("UPDATE_USER_ID in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotIn(List<String> values) {
			addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("UPDATE_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("UPDATE_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("UPDATE_DATETIME >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("UPDATE_DATETIME <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_diagnostic_dentalhistory
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 18 14:57:33 IST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}