package com.doerit.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatientRequestBiopsyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public PatientRequestBiopsyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberIsNull() {
			addCriterion("PATIENT_SERIAL_NUMBER is null");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberIsNotNull() {
			addCriterion("PATIENT_SERIAL_NUMBER is not null");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberEqualTo(String value) {
			addCriterion("PATIENT_SERIAL_NUMBER =", value, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberNotEqualTo(String value) {
			addCriterion("PATIENT_SERIAL_NUMBER <>", value, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberGreaterThan(String value) {
			addCriterion("PATIENT_SERIAL_NUMBER >", value, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberGreaterThanOrEqualTo(String value) {
			addCriterion("PATIENT_SERIAL_NUMBER >=", value, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberLessThan(String value) {
			addCriterion("PATIENT_SERIAL_NUMBER <", value, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberLessThanOrEqualTo(String value) {
			addCriterion("PATIENT_SERIAL_NUMBER <=", value, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberLike(String value) {
			addCriterion("PATIENT_SERIAL_NUMBER like", value, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberNotLike(String value) {
			addCriterion("PATIENT_SERIAL_NUMBER not like", value, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberIn(List<String> values) {
			addCriterion("PATIENT_SERIAL_NUMBER in", values, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberNotIn(List<String> values) {
			addCriterion("PATIENT_SERIAL_NUMBER not in", values, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberBetween(String value1, String value2) {
			addCriterion("PATIENT_SERIAL_NUMBER between", value1, value2, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andPatientSerialNumberNotBetween(String value1, String value2) {
			addCriterion("PATIENT_SERIAL_NUMBER not between", value1, value2, "patientSerialNumber");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryIsNull() {
			addCriterion("DATE_OF_SURGERY is null");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryIsNotNull() {
			addCriterion("DATE_OF_SURGERY is not null");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryEqualTo(Date value) {
			addCriterion("DATE_OF_SURGERY =", value, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryNotEqualTo(Date value) {
			addCriterion("DATE_OF_SURGERY <>", value, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryGreaterThan(Date value) {
			addCriterion("DATE_OF_SURGERY >", value, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryGreaterThanOrEqualTo(Date value) {
			addCriterion("DATE_OF_SURGERY >=", value, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryLessThan(Date value) {
			addCriterion("DATE_OF_SURGERY <", value, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryLessThanOrEqualTo(Date value) {
			addCriterion("DATE_OF_SURGERY <=", value, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryIn(List<Date> values) {
			addCriterion("DATE_OF_SURGERY in", values, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryNotIn(List<Date> values) {
			addCriterion("DATE_OF_SURGERY not in", values, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryBetween(Date value1, Date value2) {
			addCriterion("DATE_OF_SURGERY between", value1, value2, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andDateOfSurgeryNotBetween(Date value1, Date value2) {
			addCriterion("DATE_OF_SURGERY not between", value1, value2, "dateOfSurgery");
			return (Criteria) this;
		}

		public Criteria andClinicIsNull() {
			addCriterion("CLINIC is null");
			return (Criteria) this;
		}

		public Criteria andClinicIsNotNull() {
			addCriterion("CLINIC is not null");
			return (Criteria) this;
		}

		public Criteria andClinicEqualTo(String value) {
			addCriterion("CLINIC =", value, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicNotEqualTo(String value) {
			addCriterion("CLINIC <>", value, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicGreaterThan(String value) {
			addCriterion("CLINIC >", value, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicGreaterThanOrEqualTo(String value) {
			addCriterion("CLINIC >=", value, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicLessThan(String value) {
			addCriterion("CLINIC <", value, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicLessThanOrEqualTo(String value) {
			addCriterion("CLINIC <=", value, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicLike(String value) {
			addCriterion("CLINIC like", value, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicNotLike(String value) {
			addCriterion("CLINIC not like", value, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicIn(List<String> values) {
			addCriterion("CLINIC in", values, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicNotIn(List<String> values) {
			addCriterion("CLINIC not in", values, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicBetween(String value1, String value2) {
			addCriterion("CLINIC between", value1, value2, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicNotBetween(String value1, String value2) {
			addCriterion("CLINIC not between", value1, value2, "clinic");
			return (Criteria) this;
		}

		public Criteria andClinicianIsNull() {
			addCriterion("CLINICIAN is null");
			return (Criteria) this;
		}

		public Criteria andClinicianIsNotNull() {
			addCriterion("CLINICIAN is not null");
			return (Criteria) this;
		}

		public Criteria andClinicianEqualTo(String value) {
			addCriterion("CLINICIAN =", value, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianNotEqualTo(String value) {
			addCriterion("CLINICIAN <>", value, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianGreaterThan(String value) {
			addCriterion("CLINICIAN >", value, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianGreaterThanOrEqualTo(String value) {
			addCriterion("CLINICIAN >=", value, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianLessThan(String value) {
			addCriterion("CLINICIAN <", value, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianLessThanOrEqualTo(String value) {
			addCriterion("CLINICIAN <=", value, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianLike(String value) {
			addCriterion("CLINICIAN like", value, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianNotLike(String value) {
			addCriterion("CLINICIAN not like", value, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianIn(List<String> values) {
			addCriterion("CLINICIAN in", values, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianNotIn(List<String> values) {
			addCriterion("CLINICIAN not in", values, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianBetween(String value1, String value2) {
			addCriterion("CLINICIAN between", value1, value2, "clinician");
			return (Criteria) this;
		}

		public Criteria andClinicianNotBetween(String value1, String value2) {
			addCriterion("CLINICIAN not between", value1, value2, "clinician");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyIsNull() {
			addCriterion("TYPE_OF_BIOPSY is null");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyIsNotNull() {
			addCriterion("TYPE_OF_BIOPSY is not null");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyEqualTo(String value) {
			addCriterion("TYPE_OF_BIOPSY =", value, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyNotEqualTo(String value) {
			addCriterion("TYPE_OF_BIOPSY <>", value, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyGreaterThan(String value) {
			addCriterion("TYPE_OF_BIOPSY >", value, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyGreaterThanOrEqualTo(String value) {
			addCriterion("TYPE_OF_BIOPSY >=", value, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyLessThan(String value) {
			addCriterion("TYPE_OF_BIOPSY <", value, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyLessThanOrEqualTo(String value) {
			addCriterion("TYPE_OF_BIOPSY <=", value, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyLike(String value) {
			addCriterion("TYPE_OF_BIOPSY like", value, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyNotLike(String value) {
			addCriterion("TYPE_OF_BIOPSY not like", value, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyIn(List<String> values) {
			addCriterion("TYPE_OF_BIOPSY in", values, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyNotIn(List<String> values) {
			addCriterion("TYPE_OF_BIOPSY not in", values, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyBetween(String value1, String value2) {
			addCriterion("TYPE_OF_BIOPSY between", value1, value2, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andTypeOfBiopsyNotBetween(String value1, String value2) {
			addCriterion("TYPE_OF_BIOPSY not between", value1, value2, "typeOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyIsNull() {
			addCriterion("SITE_OF_BIOPSY is null");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyIsNotNull() {
			addCriterion("SITE_OF_BIOPSY is not null");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyEqualTo(String value) {
			addCriterion("SITE_OF_BIOPSY =", value, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyNotEqualTo(String value) {
			addCriterion("SITE_OF_BIOPSY <>", value, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyGreaterThan(String value) {
			addCriterion("SITE_OF_BIOPSY >", value, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyGreaterThanOrEqualTo(String value) {
			addCriterion("SITE_OF_BIOPSY >=", value, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyLessThan(String value) {
			addCriterion("SITE_OF_BIOPSY <", value, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyLessThanOrEqualTo(String value) {
			addCriterion("SITE_OF_BIOPSY <=", value, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyLike(String value) {
			addCriterion("SITE_OF_BIOPSY like", value, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyNotLike(String value) {
			addCriterion("SITE_OF_BIOPSY not like", value, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyIn(List<String> values) {
			addCriterion("SITE_OF_BIOPSY in", values, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyNotIn(List<String> values) {
			addCriterion("SITE_OF_BIOPSY not in", values, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyBetween(String value1, String value2) {
			addCriterion("SITE_OF_BIOPSY between", value1, value2, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andSiteOfBiopsyNotBetween(String value1, String value2) {
			addCriterion("SITE_OF_BIOPSY not between", value1, value2, "siteOfBiopsy");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisIsNull() {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS is null");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisIsNotNull() {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS is not null");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS =", value, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisNotEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS <>", value, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisGreaterThan(String value) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS >", value, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisGreaterThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS >=", value, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisLessThan(String value) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS <", value, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisLessThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS <=", value, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisLike(String value) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS like", value, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisNotLike(String value) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS not like", value, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisIn(List<String> values) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS in", values, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisNotIn(List<String> values) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS not in", values, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisBetween(String value1, String value2) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS between", value1, value2, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyDiagnosisNotBetween(String value1, String value2) {
			addCriterion("PREVIOUS_BIOPSY_DIAGNOSIS not between", value1, value2, "previousBiopsyDiagnosis");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberIsNull() {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER is null");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberIsNotNull() {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER is not null");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER =", value, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberNotEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER <>", value, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberGreaterThan(String value) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER >", value, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberGreaterThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER >=", value, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberLessThan(String value) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER <", value, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberLessThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER <=", value, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberLike(String value) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER like", value, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberNotLike(String value) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER not like", value, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberIn(List<String> values) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER in", values, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberNotIn(List<String> values) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER not in", values, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberBetween(String value1, String value2) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER between", value1, value2, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyPathNumberNotBetween(String value1, String value2) {
			addCriterion("PREVIOUS_BIOPSY_PATH_NUMBER not between", value1, value2, "previousBiopsyPathNumber");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeIsNull() {
			addCriterion("PREVIOUS_BIOPSY_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeIsNotNull() {
			addCriterion("PREVIOUS_BIOPSY_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_TYPE =", value, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeNotEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_TYPE <>", value, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeGreaterThan(String value) {
			addCriterion("PREVIOUS_BIOPSY_TYPE >", value, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeGreaterThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_TYPE >=", value, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeLessThan(String value) {
			addCriterion("PREVIOUS_BIOPSY_TYPE <", value, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeLessThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_TYPE <=", value, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeLike(String value) {
			addCriterion("PREVIOUS_BIOPSY_TYPE like", value, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeNotLike(String value) {
			addCriterion("PREVIOUS_BIOPSY_TYPE not like", value, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeIn(List<String> values) {
			addCriterion("PREVIOUS_BIOPSY_TYPE in", values, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeNotIn(List<String> values) {
			addCriterion("PREVIOUS_BIOPSY_TYPE not in", values, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeBetween(String value1, String value2) {
			addCriterion("PREVIOUS_BIOPSY_TYPE between", value1, value2, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsyTypeNotBetween(String value1, String value2) {
			addCriterion("PREVIOUS_BIOPSY_TYPE not between", value1, value2, "previousBiopsyType");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteIsNull() {
			addCriterion("PREVIOUS_BIOPSY_SITE is null");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteIsNotNull() {
			addCriterion("PREVIOUS_BIOPSY_SITE is not null");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_SITE =", value, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteNotEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_SITE <>", value, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteGreaterThan(String value) {
			addCriterion("PREVIOUS_BIOPSY_SITE >", value, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteGreaterThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_SITE >=", value, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteLessThan(String value) {
			addCriterion("PREVIOUS_BIOPSY_SITE <", value, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteLessThanOrEqualTo(String value) {
			addCriterion("PREVIOUS_BIOPSY_SITE <=", value, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteLike(String value) {
			addCriterion("PREVIOUS_BIOPSY_SITE like", value, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteNotLike(String value) {
			addCriterion("PREVIOUS_BIOPSY_SITE not like", value, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteIn(List<String> values) {
			addCriterion("PREVIOUS_BIOPSY_SITE in", values, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteNotIn(List<String> values) {
			addCriterion("PREVIOUS_BIOPSY_SITE not in", values, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteBetween(String value1, String value2) {
			addCriterion("PREVIOUS_BIOPSY_SITE between", value1, value2, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andPreviousBiopsySiteNotBetween(String value1, String value2) {
			addCriterion("PREVIOUS_BIOPSY_SITE not between", value1, value2, "previousBiopsySite");
			return (Criteria) this;
		}

		public Criteria andDurationIsNull() {
			addCriterion("DURATION is null");
			return (Criteria) this;
		}

		public Criteria andDurationIsNotNull() {
			addCriterion("DURATION is not null");
			return (Criteria) this;
		}

		public Criteria andDurationEqualTo(String value) {
			addCriterion("DURATION =", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotEqualTo(String value) {
			addCriterion("DURATION <>", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThan(String value) {
			addCriterion("DURATION >", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThanOrEqualTo(String value) {
			addCriterion("DURATION >=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThan(String value) {
			addCriterion("DURATION <", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThanOrEqualTo(String value) {
			addCriterion("DURATION <=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLike(String value) {
			addCriterion("DURATION like", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotLike(String value) {
			addCriterion("DURATION not like", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationIn(List<String> values) {
			addCriterion("DURATION in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotIn(List<String> values) {
			addCriterion("DURATION not in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationBetween(String value1, String value2) {
			addCriterion("DURATION between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotBetween(String value1, String value2) {
			addCriterion("DURATION not between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionIsNull() {
			addCriterion("SITE_OF_LESSION is null");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionIsNotNull() {
			addCriterion("SITE_OF_LESSION is not null");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionEqualTo(String value) {
			addCriterion("SITE_OF_LESSION =", value, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionNotEqualTo(String value) {
			addCriterion("SITE_OF_LESSION <>", value, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionGreaterThan(String value) {
			addCriterion("SITE_OF_LESSION >", value, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionGreaterThanOrEqualTo(String value) {
			addCriterion("SITE_OF_LESSION >=", value, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionLessThan(String value) {
			addCriterion("SITE_OF_LESSION <", value, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionLessThanOrEqualTo(String value) {
			addCriterion("SITE_OF_LESSION <=", value, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionLike(String value) {
			addCriterion("SITE_OF_LESSION like", value, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionNotLike(String value) {
			addCriterion("SITE_OF_LESSION not like", value, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionIn(List<String> values) {
			addCriterion("SITE_OF_LESSION in", values, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionNotIn(List<String> values) {
			addCriterion("SITE_OF_LESSION not in", values, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionBetween(String value1, String value2) {
			addCriterion("SITE_OF_LESSION between", value1, value2, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andSiteOfLessionNotBetween(String value1, String value2) {
			addCriterion("SITE_OF_LESSION not between", value1, value2, "siteOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionIsNull() {
			addCriterion("TYPE_OF_LESSION is null");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionIsNotNull() {
			addCriterion("TYPE_OF_LESSION is not null");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionEqualTo(String value) {
			addCriterion("TYPE_OF_LESSION =", value, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionNotEqualTo(String value) {
			addCriterion("TYPE_OF_LESSION <>", value, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionGreaterThan(String value) {
			addCriterion("TYPE_OF_LESSION >", value, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionGreaterThanOrEqualTo(String value) {
			addCriterion("TYPE_OF_LESSION >=", value, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionLessThan(String value) {
			addCriterion("TYPE_OF_LESSION <", value, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionLessThanOrEqualTo(String value) {
			addCriterion("TYPE_OF_LESSION <=", value, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionLike(String value) {
			addCriterion("TYPE_OF_LESSION like", value, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionNotLike(String value) {
			addCriterion("TYPE_OF_LESSION not like", value, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionIn(List<String> values) {
			addCriterion("TYPE_OF_LESSION in", values, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionNotIn(List<String> values) {
			addCriterion("TYPE_OF_LESSION not in", values, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionBetween(String value1, String value2) {
			addCriterion("TYPE_OF_LESSION between", value1, value2, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andTypeOfLessionNotBetween(String value1, String value2) {
			addCriterion("TYPE_OF_LESSION not between", value1, value2, "typeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionIsNull() {
			addCriterion("SIZE_OF_LESSION is null");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionIsNotNull() {
			addCriterion("SIZE_OF_LESSION is not null");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionEqualTo(String value) {
			addCriterion("SIZE_OF_LESSION =", value, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionNotEqualTo(String value) {
			addCriterion("SIZE_OF_LESSION <>", value, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionGreaterThan(String value) {
			addCriterion("SIZE_OF_LESSION >", value, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionGreaterThanOrEqualTo(String value) {
			addCriterion("SIZE_OF_LESSION >=", value, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionLessThan(String value) {
			addCriterion("SIZE_OF_LESSION <", value, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionLessThanOrEqualTo(String value) {
			addCriterion("SIZE_OF_LESSION <=", value, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionLike(String value) {
			addCriterion("SIZE_OF_LESSION like", value, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionNotLike(String value) {
			addCriterion("SIZE_OF_LESSION not like", value, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionIn(List<String> values) {
			addCriterion("SIZE_OF_LESSION in", values, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionNotIn(List<String> values) {
			addCriterion("SIZE_OF_LESSION not in", values, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionBetween(String value1, String value2) {
			addCriterion("SIZE_OF_LESSION between", value1, value2, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andSizeOfLessionNotBetween(String value1, String value2) {
			addCriterion("SIZE_OF_LESSION not between", value1, value2, "sizeOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionIsNull() {
			addCriterion("COLOR_OF_LESSION is null");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionIsNotNull() {
			addCriterion("COLOR_OF_LESSION is not null");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionEqualTo(String value) {
			addCriterion("COLOR_OF_LESSION =", value, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionNotEqualTo(String value) {
			addCriterion("COLOR_OF_LESSION <>", value, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionGreaterThan(String value) {
			addCriterion("COLOR_OF_LESSION >", value, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionGreaterThanOrEqualTo(String value) {
			addCriterion("COLOR_OF_LESSION >=", value, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionLessThan(String value) {
			addCriterion("COLOR_OF_LESSION <", value, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionLessThanOrEqualTo(String value) {
			addCriterion("COLOR_OF_LESSION <=", value, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionLike(String value) {
			addCriterion("COLOR_OF_LESSION like", value, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionNotLike(String value) {
			addCriterion("COLOR_OF_LESSION not like", value, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionIn(List<String> values) {
			addCriterion("COLOR_OF_LESSION in", values, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionNotIn(List<String> values) {
			addCriterion("COLOR_OF_LESSION not in", values, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionBetween(String value1, String value2) {
			addCriterion("COLOR_OF_LESSION between", value1, value2, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andColorOfLessionNotBetween(String value1, String value2) {
			addCriterion("COLOR_OF_LESSION not between", value1, value2, "colorOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionIsNull() {
			addCriterion("SHAPE_OF_LESSION is null");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionIsNotNull() {
			addCriterion("SHAPE_OF_LESSION is not null");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionEqualTo(String value) {
			addCriterion("SHAPE_OF_LESSION =", value, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionNotEqualTo(String value) {
			addCriterion("SHAPE_OF_LESSION <>", value, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionGreaterThan(String value) {
			addCriterion("SHAPE_OF_LESSION >", value, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionGreaterThanOrEqualTo(String value) {
			addCriterion("SHAPE_OF_LESSION >=", value, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionLessThan(String value) {
			addCriterion("SHAPE_OF_LESSION <", value, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionLessThanOrEqualTo(String value) {
			addCriterion("SHAPE_OF_LESSION <=", value, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionLike(String value) {
			addCriterion("SHAPE_OF_LESSION like", value, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionNotLike(String value) {
			addCriterion("SHAPE_OF_LESSION not like", value, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionIn(List<String> values) {
			addCriterion("SHAPE_OF_LESSION in", values, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionNotIn(List<String> values) {
			addCriterion("SHAPE_OF_LESSION not in", values, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionBetween(String value1, String value2) {
			addCriterion("SHAPE_OF_LESSION between", value1, value2, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andShapeOfLessionNotBetween(String value1, String value2) {
			addCriterion("SHAPE_OF_LESSION not between", value1, value2, "shapeOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionIsNull() {
			addCriterion("CONSISTENCY_OF_LESSION is null");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionIsNotNull() {
			addCriterion("CONSISTENCY_OF_LESSION is not null");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionEqualTo(String value) {
			addCriterion("CONSISTENCY_OF_LESSION =", value, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionNotEqualTo(String value) {
			addCriterion("CONSISTENCY_OF_LESSION <>", value, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionGreaterThan(String value) {
			addCriterion("CONSISTENCY_OF_LESSION >", value, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionGreaterThanOrEqualTo(String value) {
			addCriterion("CONSISTENCY_OF_LESSION >=", value, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionLessThan(String value) {
			addCriterion("CONSISTENCY_OF_LESSION <", value, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionLessThanOrEqualTo(String value) {
			addCriterion("CONSISTENCY_OF_LESSION <=", value, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionLike(String value) {
			addCriterion("CONSISTENCY_OF_LESSION like", value, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionNotLike(String value) {
			addCriterion("CONSISTENCY_OF_LESSION not like", value, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionIn(List<String> values) {
			addCriterion("CONSISTENCY_OF_LESSION in", values, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionNotIn(List<String> values) {
			addCriterion("CONSISTENCY_OF_LESSION not in", values, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionBetween(String value1, String value2) {
			addCriterion("CONSISTENCY_OF_LESSION between", value1, value2, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andConsistencyOfLessionNotBetween(String value1, String value2) {
			addCriterion("CONSISTENCY_OF_LESSION not between", value1, value2, "consistencyOfLession");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionIsNull() {
			addCriterion("CLINICAL_IMPRESSION is null");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionIsNotNull() {
			addCriterion("CLINICAL_IMPRESSION is not null");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionEqualTo(String value) {
			addCriterion("CLINICAL_IMPRESSION =", value, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionNotEqualTo(String value) {
			addCriterion("CLINICAL_IMPRESSION <>", value, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionGreaterThan(String value) {
			addCriterion("CLINICAL_IMPRESSION >", value, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionGreaterThanOrEqualTo(String value) {
			addCriterion("CLINICAL_IMPRESSION >=", value, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionLessThan(String value) {
			addCriterion("CLINICAL_IMPRESSION <", value, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionLessThanOrEqualTo(String value) {
			addCriterion("CLINICAL_IMPRESSION <=", value, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionLike(String value) {
			addCriterion("CLINICAL_IMPRESSION like", value, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionNotLike(String value) {
			addCriterion("CLINICAL_IMPRESSION not like", value, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionIn(List<String> values) {
			addCriterion("CLINICAL_IMPRESSION in", values, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionNotIn(List<String> values) {
			addCriterion("CLINICAL_IMPRESSION not in", values, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionBetween(String value1, String value2) {
			addCriterion("CLINICAL_IMPRESSION between", value1, value2, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andClinicalImpressionNotBetween(String value1, String value2) {
			addCriterion("CLINICAL_IMPRESSION not between", value1, value2, "clinicalImpression");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingIsNull() {
			addCriterion("RADIOLOGICAL_FINDING is null");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingIsNotNull() {
			addCriterion("RADIOLOGICAL_FINDING is not null");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingEqualTo(String value) {
			addCriterion("RADIOLOGICAL_FINDING =", value, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingNotEqualTo(String value) {
			addCriterion("RADIOLOGICAL_FINDING <>", value, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingGreaterThan(String value) {
			addCriterion("RADIOLOGICAL_FINDING >", value, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingGreaterThanOrEqualTo(String value) {
			addCriterion("RADIOLOGICAL_FINDING >=", value, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingLessThan(String value) {
			addCriterion("RADIOLOGICAL_FINDING <", value, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingLessThanOrEqualTo(String value) {
			addCriterion("RADIOLOGICAL_FINDING <=", value, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingLike(String value) {
			addCriterion("RADIOLOGICAL_FINDING like", value, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingNotLike(String value) {
			addCriterion("RADIOLOGICAL_FINDING not like", value, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingIn(List<String> values) {
			addCriterion("RADIOLOGICAL_FINDING in", values, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingNotIn(List<String> values) {
			addCriterion("RADIOLOGICAL_FINDING not in", values, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingBetween(String value1, String value2) {
			addCriterion("RADIOLOGICAL_FINDING between", value1, value2, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andRadiologicalFindingNotBetween(String value1, String value2) {
			addCriterion("RADIOLOGICAL_FINDING not between", value1, value2, "radiologicalFinding");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("COMMENT is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("COMMENT is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("COMMENT =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("COMMENT <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("COMMENT >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("COMMENT >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("COMMENT <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("COMMENT <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("COMMENT like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("COMMENT not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("COMMENT in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("COMMENT not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("COMMENT between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("COMMENT not between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNull() {
			addCriterion("SORT_ORDER is null");
			return (Criteria) this;
		}

		public Criteria andSortOrderIsNotNull() {
			addCriterion("SORT_ORDER is not null");
			return (Criteria) this;
		}

		public Criteria andSortOrderEqualTo(Integer value) {
			addCriterion("SORT_ORDER =", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotEqualTo(Integer value) {
			addCriterion("SORT_ORDER <>", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThan(Integer value) {
			addCriterion("SORT_ORDER >", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER >=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThan(Integer value) {
			addCriterion("SORT_ORDER <", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER <=", value, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderIn(List<Integer> values) {
			addCriterion("SORT_ORDER in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotIn(List<Integer> values) {
			addCriterion("SORT_ORDER not in", values, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER not between", value1, value2, "sortOrder");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNull() {
			addCriterion("INSERT_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIsNotNull() {
			addCriterion("INSERT_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdEqualTo(String value) {
			addCriterion("INSERT_USER_ID =", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotEqualTo(String value) {
			addCriterion("INSERT_USER_ID <>", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThan(String value) {
			addCriterion("INSERT_USER_ID >", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID >=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThan(String value) {
			addCriterion("INSERT_USER_ID <", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
			addCriterion("INSERT_USER_ID <=", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdLike(String value) {
			addCriterion("INSERT_USER_ID like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotLike(String value) {
			addCriterion("INSERT_USER_ID not like", value, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdIn(List<String> values) {
			addCriterion("INSERT_USER_ID in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotIn(List<String> values) {
			addCriterion("INSERT_USER_ID not in", values, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andInsertUserIdNotBetween(String value1, String value2) {
			addCriterion("INSERT_USER_ID not between", value1, value2, "insertUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNull() {
			addCriterion("UPDATE_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNotNull() {
			addCriterion("UPDATE_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdEqualTo(String value) {
			addCriterion("UPDATE_USER_ID =", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThan(String value) {
			addCriterion("UPDATE_USER_ID >", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThan(String value) {
			addCriterion("UPDATE_USER_ID <", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLike(String value) {
			addCriterion("UPDATE_USER_ID like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotLike(String value) {
			addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIn(List<String> values) {
			addCriterion("UPDATE_USER_ID in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotIn(List<String> values) {
			addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("INSERT_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("INSERT_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("INSERT_DATETIME =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("INSERT_DATETIME >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("INSERT_DATETIME <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATETIME <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("INSERT_DATETIME in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("INSERT_DATETIME not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATETIME not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("UPDATE_DATETIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("UPDATE_DATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("UPDATE_DATETIME >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("UPDATE_DATETIME <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATETIME <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("UPDATE_DATETIME not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATETIME not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_patient_request_biopsy
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 22 10:29:08 IST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}