package com.doerit.dao;

import com.doerit.model.PatientDiagnosticBrushingHabits;
import com.doerit.model.PatientDiagnosticBrushingHabitsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientDiagnosticBrushingHabitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    long countByExample(PatientDiagnosticBrushingHabitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    int deleteByExample(PatientDiagnosticBrushingHabitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    int insert(PatientDiagnosticBrushingHabits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    int insertSelective(PatientDiagnosticBrushingHabits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    List<PatientDiagnosticBrushingHabits> selectByExample(PatientDiagnosticBrushingHabitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    PatientDiagnosticBrushingHabits selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    int updateByExampleSelective(@Param("record") PatientDiagnosticBrushingHabits record, @Param("example") PatientDiagnosticBrushingHabitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    int updateByExample(@Param("record") PatientDiagnosticBrushingHabits record, @Param("example") PatientDiagnosticBrushingHabitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    int updateByPrimaryKeySelective(PatientDiagnosticBrushingHabits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_brushing_habits
     *
     * @mbg.generated Tue Apr 24 15:45:48 IST 2018
     */
    int updateByPrimaryKey(PatientDiagnosticBrushingHabits record);
}