package com.doerit.dao;

import com.doerit.model.PatientMissingTeeth;
import com.doerit.model.PatientMissingTeethExample;
import com.doerit.model.PatientMissingTeethWithBLOBs;
import com.doerit.util.Pager;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

public interface PatientMissingTeethMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	long countByExample(PatientMissingTeethExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int deleteByExample(PatientMissingTeethExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int insert(PatientMissingTeeth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int insertSelective(PatientMissingTeeth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	List<PatientMissingTeeth> selectByExampleWithBLOBs(PatientMissingTeethExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	List<PatientMissingTeeth> selectByExample(PatientMissingTeethExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	PatientMissingTeeth selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int updateByExampleSelective(@Param("record") PatientMissingTeeth record,
			@Param("example") PatientMissingTeethExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") PatientMissingTeeth record,
			@Param("example") PatientMissingTeethExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int updateByExample(@Param("record") PatientMissingTeeth record,
			@Param("example") PatientMissingTeethExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int updateByPrimaryKeySelective(PatientMissingTeeth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(PatientMissingTeeth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_missing_teeth
	 * @mbg.generated  Thu Jul 19 10:49:40 IST 2018
	 */
	int updateByPrimaryKey(PatientMissingTeeth record);

  /**
   * @param p
   * @param patientId
   * @param state
   * @return
   */
  @Select("SELECT * FROM tbl_patient_missing_teeth WHERE PATIENT_ID = #{patientId} AND STATUS =#{state} order by INSERT_DATETIME desc"
      + " LIMIT #{pager.start}, #{pager.limit}")
  @ResultMap("BaseResultMap")
  List<PatientMissingTeeth> viewAllByPagerAndPatientIdAndStatus(@Param("pager") Pager p,
      @Param("patientId") String patientId, @Param("state") byte state);

	
  /**
   * @param patientId
   * @param state
   * @return
   */
  @Select("SELECT count(0) from tbl_patient_missing_teeth WHERE PATIENT_ID = #{patientId} AND #{state}")
  Integer countAllByPagerAndPatientIdAndStatus(@Param("patientId")String patientId, @Param("state")byte state);

  //select record count for patient id
  @Select("SELECT count(0) from tbl_patient_missing_teeth WHERE PATIENT_ID = #{patientId} AND #{state}")
  Integer countAllByPatientIdAndStatus(@Param("patientId")String patientId, @Param("state")byte state);

  /**
   * @param patientId
   */
  
  @Select (" SELECT * FROM tbl_patient_missing_teeth WHERE PATIENT_ID = #{patientId} order by INSERT_DATETIME DESC LIMIT 1")
  @ResultMap("BaseResultMap")
  PatientMissingTeeth selectByPatientIdAndRecentDate(@Param("patientId") String patientId);
}

