package com.doerit.dao;

import com.doerit.model.PatientReportPathology;
import com.doerit.model.PatientReportPathologyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import com.doerit.model.PatientReportPathologyWithBLOBs;
import com.doerit.util.Pager;

public interface PatientReportPathologyMapper {
  
	 @Select("SELECT c.* " + 
	    		" FROM tbl_patient_report_pathology c " +  
	    		" WHERE c.STATUS = #{status} " + 
	    		" ORDER BY INSERT_DATETIME DESC " +
	    		" LIMIT #{pager.start}, #{pager.limit}")
	    @ResultMap("BaseResultMap")
		List<PatientReportPathology> viewAllByStatus(@Param("pager")Pager pager,  @Param("status")byte status);
	    
	    @Select("SELECT count(0) " + 
	    		" FROM tbl_patient_report_pathology c " +  
	    		" WHERE c.STATUS = #{status}")
		Integer countAllByStatus(@Param("status")byte status);
	    
	long countByExample(PatientReportPathologyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int deleteByExample(PatientReportPathologyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int insert(PatientReportPathologyWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int insertSelective(PatientReportPathologyWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	List<PatientReportPathologyWithBLOBs> selectByExampleWithBLOBs(PatientReportPathologyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	List<PatientReportPathology> selectByExample(PatientReportPathologyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	PatientReportPathologyWithBLOBs selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int updateByExampleSelective(@Param("record") PatientReportPathologyWithBLOBs record,
			@Param("example") PatientReportPathologyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") PatientReportPathologyWithBLOBs record,
			@Param("example") PatientReportPathologyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int updateByExample(@Param("record") PatientReportPathology record,
			@Param("example") PatientReportPathologyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int updateByPrimaryKeySelective(PatientReportPathologyWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(PatientReportPathologyWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_report_pathology
	 * @mbg.generated  Wed Feb 07 14:22:10 IST 2018
	 */
	int updateByPrimaryKey(PatientReportPathology record);

	@Select("Select * FROM tbl_patient_report_pathology WHERE PATIENT_ID = #{patientId} ORDER BY REPORT_DATE DESC")
    @ResultMap("BaseResultMap")
    List<PatientReportPathologyWithBLOBs> findByPatientId(@Param("patientId")String patientId);
    
}