package com.doerit.dao;

import com.doerit.model.Patient;
import com.doerit.model.PatientTeethDisorder;
import com.doerit.model.PatientTeethDisorderExample;
import com.doerit.util.Pager;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

public interface PatientTeethDisorderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	long countByExample(PatientTeethDisorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	int deleteByExample(PatientTeethDisorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	int insert(PatientTeethDisorder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	int insertSelective(PatientTeethDisorder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	List<PatientTeethDisorder> selectByExample(
			PatientTeethDisorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	PatientTeethDisorder selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	int updateByExampleSelective(@Param("record") PatientTeethDisorder record,
			@Param("example") PatientTeethDisorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	int updateByExample(@Param("record") PatientTeethDisorder record,
			@Param("example") PatientTeethDisorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	int updateByPrimaryKeySelective(PatientTeethDisorder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_teeth_disorder
	 * @mbg.generated  Wed Aug 29 12:00:35 IST 2018
	 */
	int updateByPrimaryKey(PatientTeethDisorder record);

	/**
	 * @param p
	 * @param patientId
	 * @return
	 */
	
	
	@Select("SELECT c.* FROM tbl_patient_teeth_disorder c"
			+ " WHERE c.PATIENT_ID = #{patientId}"
			+ " LIMIT #{pager.start}, #{pager.limit}")
	 @ResultMap("BaseResultMap")
	List<PatientTeethDisorder> viewAllByPatientId(@Param("pager")Pager p, @Param("patientId")String patientId);

	/**
	 * @param patientId
	 * @return
	 */
	@Select("SELECT count(0) FROM tbl_patient_teeth_disorder c"
			+ " WHERE c.PATIENT_ID = #{patientId}")
	Integer countAllByPatientId(@Param("patientId")String patientId);
}