package com.doerit.dao;

import com.doerit.model.PatientDiagnosticDentalHistory;
import com.doerit.model.PatientDiagnosticDentalHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientDiagnosticDentalHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	long countByExample(PatientDiagnosticDentalHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	int deleteByExample(PatientDiagnosticDentalHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	int deleteByPrimaryKey(String id);

	
	int insert(PatientDiagnosticDentalHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	int insertSelective(PatientDiagnosticDentalHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	List<PatientDiagnosticDentalHistory> selectByExample(PatientDiagnosticDentalHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	PatientDiagnosticDentalHistory selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	int updateByExampleSelective(@Param("record") PatientDiagnosticDentalHistory record,
			@Param("example") PatientDiagnosticDentalHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	int updateByExample(@Param("record") PatientDiagnosticDentalHistory record,
			@Param("example") PatientDiagnosticDentalHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	int updateByPrimaryKeySelective(PatientDiagnosticDentalHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_dentalhistory
	 * @mbg.generated  Sun May 06 15:34:18 IST 2018
	 */
	int updateByPrimaryKey(PatientDiagnosticDentalHistory record);
}