package com.doerit.dao;

import com.doerit.model.PatientDiagnosticMedicalRecord2;
import com.doerit.model.PatientDiagnosticMedicalRecord2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientDiagnosticMedicalRecord2Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	long countByExample(PatientDiagnosticMedicalRecord2Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	int deleteByExample(PatientDiagnosticMedicalRecord2Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	int insert(PatientDiagnosticMedicalRecord2 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	int insertSelective(PatientDiagnosticMedicalRecord2 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	List<PatientDiagnosticMedicalRecord2> selectByExample(PatientDiagnosticMedicalRecord2Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	PatientDiagnosticMedicalRecord2 selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	int updateByExampleSelective(@Param("record") PatientDiagnosticMedicalRecord2 record,
			@Param("example") PatientDiagnosticMedicalRecord2Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	int updateByExample(@Param("record") PatientDiagnosticMedicalRecord2 record,
			@Param("example") PatientDiagnosticMedicalRecord2Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	int updateByPrimaryKeySelective(PatientDiagnosticMedicalRecord2 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_diagnostic_medicalrecord2
	 * @mbg.generated  Sun May 06 16:54:35 IST 2018
	 */
	int updateByPrimaryKey(PatientDiagnosticMedicalRecord2 record);
    
    
}