package com.doerit.dao;

import com.doerit.model.PatientDiagnosticDrug;
import com.doerit.model.PatientDiagnosticDrugExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

public interface PatientDiagnosticDrugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    long countByExample(PatientDiagnosticDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    int deleteByExample(PatientDiagnosticDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    int insert(PatientDiagnosticDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    int insertSelective(PatientDiagnosticDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    List<PatientDiagnosticDrug> selectByExample(PatientDiagnosticDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    PatientDiagnosticDrug selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    int updateByExampleSelective(@Param("record") PatientDiagnosticDrug record, @Param("example") PatientDiagnosticDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    int updateByExample(@Param("record") PatientDiagnosticDrug record, @Param("example") PatientDiagnosticDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    int updateByPrimaryKeySelective(PatientDiagnosticDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_diagnostic_drug
     *
     * @mbg.generated Fri May 11 13:21:27 IST 2018
     */
    int updateByPrimaryKey(PatientDiagnosticDrug record);
    
    @Select("SELECT * FROM tbl_patient_diagnostic_drug WHERE DRUGHISTORY_ID = #{historyId}")
    @ResultMap("BaseResultMap")
    List<PatientDiagnosticDrug> findByDrugHistoryId(@Param("historyId")String drugHistoryId);

	/**
	 * 
	 */
    

}