package com.doerit.dao;

import com.doerit.model.PatientRequestHBI;
import com.doerit.model.PatientRequestHBIExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

public interface PatientRequestHBIMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    long countByExample(PatientRequestHBIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    int deleteByExample(PatientRequestHBIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    int insert(PatientRequestHBI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    int insertSelective(PatientRequestHBI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    List<PatientRequestHBI> selectByExample(PatientRequestHBIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    PatientRequestHBI selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    int updateByExampleSelective(@Param("record") PatientRequestHBI record, @Param("example") PatientRequestHBIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    int updateByExample(@Param("record") PatientRequestHBI record, @Param("example") PatientRequestHBIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    int updateByPrimaryKeySelective(PatientRequestHBI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_patient_request_hbi
     *
     * @mbg.generated Mon Feb 19 13:20:22 IST 2018
     */
    int updateByPrimaryKey(PatientRequestHBI record);

    /**
     * @param databaseValue
     * @return
     */
    
    @Select("SELECT * FROM tbl_patient_request_hbi")
    @ResultMap("BaseResultMap")
    List<PatientRequestHBI> viewAllByStatus(@Param("status")byte databaseValue);

    /**
     * @param databaseValue
     * @return
     */
    @Select("SELECT count(*) FROM tbl_patient_request_hbi WHERE STATUS =#{status} ")
    Integer countAllByStatus(@Param("status")byte databaseValue);
}