package com.doerit.dao;

import com.doerit.model.PatientRequestBiopsy;
import com.doerit.model.PatientRequestBiopsyExample;
import com.doerit.util.Pager;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

public interface PatientRequestBiopsyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	long countByExample(PatientRequestBiopsyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	int deleteByExample(PatientRequestBiopsyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	int insert(PatientRequestBiopsy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	int insertSelective(PatientRequestBiopsy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	List<PatientRequestBiopsy> selectByExample(PatientRequestBiopsyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	PatientRequestBiopsy selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	int updateByExampleSelective(@Param("record") PatientRequestBiopsy record,
			@Param("example") PatientRequestBiopsyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	int updateByExample(@Param("record") PatientRequestBiopsy record,
			@Param("example") PatientRequestBiopsyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	int updateByPrimaryKeySelective(PatientRequestBiopsy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_patient_request_biopsy
	 * @mbg.generated  Tue May 01 10:12:29 IST 2018
	 */
	int updateByPrimaryKey(PatientRequestBiopsy record);

	/*	@Select("Select * FROM tbl_patient_request_biopsy WHERE PATIENT_ID = #{patientId} ORDER BY INSERT_DATETIME DESC")
    @ResultMap("BaseResultMap")*/
	List<PatientRequestBiopsy> findByPatientId(String patientId);

/*    @Select("SELECT c.* " + 
    		" FROM tbl_patient_request_biopsy c " +  
    		" WHERE c.STATUS = #{status} " + 
    		" ORDER BY INSERT_DATETIME DESC " +
    		" LIMIT #{pager.start}, #{pager.limit}"    		
    		)
    @ResultMap("BaseResultMap")	*/
	List<PatientRequestBiopsy> viewAllByStatus(Pager p, byte state);


    @Select("SELECT count(0) " + 
    		" FROM tbl_patient_request_biopsy c " +  
    		" WHERE c.STATUS = #{status}")
	Integer countAllByStatus(@Param("status")byte status);     
    
    
    
    
}