package com.doerit.dao;

import com.doerit.model.UserAccount;
import com.doerit.model.UserAccountExample;
import com.doerit.util.Pager;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

public interface UserAccountMapper {

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	long countByExample(UserAccountExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	
	int deleteByExample(UserAccountExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	int deleteByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	int insert(UserAccount record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	int insertSelective(UserAccount record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	List<UserAccount> selectByExample(UserAccountExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	UserAccount selectByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	int updateByExampleSelective(@Param("record") UserAccount record, @Param("example") UserAccountExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	int updateByExample(@Param("record") UserAccount record, @Param("example") UserAccountExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
	int updateByPrimaryKeySelective(UserAccount record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user_account
	 * @mbg.generated  Thu May 17 15:47:38 IST 2018
	 */
    
    @Select("SELECT ID, USER_NAME, CATEGORY_RELATION_ID, RELATION_ID, STATUS "
    		+ "FROM tbl_user_account WHERE USER_NAME = #{userName} AND "
    		+ "USER_PASSWORD = #{password} AND STATUS = #{status}")
    @ResultMap("BaseResultMap")
	UserAccount findByEmailPasswordAndState(@Param("userName")String userName, 
			@Param("password")String password, @Param("status")byte databaseValue);

    @Select("SELECT ID, USER_NAME, CATEGORY_RELATION_ID, RELATION_ID, STATUS "
    		+ "FROM tbl_user_account WHERE  STATUS = #{status}")
    @ResultMap("BaseResultMap")
	List<UserAccount> findByState(@Param("status")byte state);
	
    @Select("SELECT * " + 
    		" FROM tbl_user_account " +  
    		" WHERE STATUS = #{status} " + 
    		" LIMIT #{pager.start}, #{pager.limit}")
    @ResultMap("BaseResultMap")
    List<UserAccount> viewAllByStatus(@Param("pager")Pager pager,  @Param("status")byte state);
    
    @Select("SELECT count(0) " + 
    		" FROM tbl_user_account c " +  
    		" WHERE c.STATUS = #{status}")
	Integer countAllByStatus(@Param("status")byte state);   

}